export const HELP_ROLE_LABELS = Object.freeze({
  administrator: "Administrator",
  operator: "Operator",
  viewer: "Viewer",
  auditor: "Auditor",
});

export const HELP_ALL_ROLES = Object.freeze(Object.keys(HELP_ROLE_LABELS));

const allRoles = () => [...HELP_ALL_ROLES];

export const HELP_MANUAL = Object.freeze({
  title: "ALPR Database Community User Guide",
  shortTitle: "User Guide",
  description:
    "A practical guide to viewing plate activity, reviewing OCR results, managing known plates, exporting records, and safely administering your ALPR installation.",
  manualVersion: "1.56",
  updatedAt: "August 8, 2026",
  coverageBaseline: "August 8, 2026 daytime overview Vehicle View candidate: independent Street Overview motion alerts and configured Entry LPR fallbacks are screened locally, associated to daytime plate reads through validated Blue Iris direction plus camera-pair timing, and never processed at night; plus the Blue Iris-primary direction release, August 7 zone-crossing foundation, August 4 storage-maintenance, August 2 production-active backup, Live Feed review, storage, privacy, maintenance, notification, and Phase 2 baseline",
  filename: "ALPR-Database-Community-User-Guide.pdf",
  sections: [
    {
      id: "getting-started",
      title: "Getting started",
      summary: "Sign in safely, change a temporary password, and learn the basic page layout.",
      roles: allRoles(),
      keywords: ["login", "password", "sign in", "navigation", "first login"],
      blocks: [
        {
          type: "steps",
          title: "Sign in",
          items: [
            "Open the ALPR website and enter your username and password on the Sign In page.",
            "Use the eye button to reveal the password only when you are sure nobody else can see the screen.",
            "Select Sign In. If the password is incorrect, the password field clears automatically and receives focus so you can try again.",
            "If your account has a temporary password, follow the prompt to choose a new password. You will then return to Sign In and use the new password.",
          ],
        },
        {
          type: "bullets",
          title: "What you will see",
          items: [
            "Desktop: the icon bar on the left opens the pages your role can use. Hover over an icon to see its name.",
            "Phone or tablet: the most common pages appear in the bottom bar. Select More for the complete menu.",
            "On a large screen, place the pointer over In this guide and scroll to move through help topics without moving the article.",
            "Settings is available to every named user for personal account changes; administrative sections appear only when the account has the required permission.",
            "If a direct link opens the Forbidden page, the account is signed in but its role does not permit that operation.",
          ],
        },
        {
          type: "note",
          tone: "info",
          title: "Keep credentials private",
          text: "Do not paste passwords, session cookies, API credentials, broker passwords, or database credentials into chat, screenshots, issue reports, or exported notes.",
        },
      ],
    },
    {
      id: "roles-and-access",
      title: "Users, roles, and access",
      summary: "Choose the least-privilege role and understand which pages each role can use.",
      roles: allRoles(),
      keywords: ["administrator", "operator", "viewer", "auditor", "permission", "user"],
      blocks: [
        {
          type: "bullets",
          title: "Built-in roles",
          items: [
            "Administrator: full configuration, integrations, users, maintenance, audit, exports, and plate operations.",
            "Operator: view plate activity, review or correct reads, and manage known plates and tags. Operators cannot administer users, MQTT, notifications, exports, audit, or maintenance.",
            "Viewer: read-only access to plate pages. Viewer navigation intentionally omits mutation and administrative controls.",
            "Auditor: read-only plate pages plus database exports and System Logs/audit access. Auditors cannot change plates or configuration.",
          ],
        },
        {
          type: "example",
          title: "Example: choose a role for a new user",
          scenario: "A person needs to investigate plate activity and download records, but must not change labels, tags, users, or integrations.",
          steps: [
            "Choose Auditor because it grants plate reading, exports, and audit visibility.",
            "Do not choose Administrator merely to expose one missing page.",
            "After creating the account, sign in as that user on staging and verify both allowed and forbidden pages.",
          ],
          result: "The user can investigate and export without receiving mutation or system-management authority.",
        },
        {
          type: "note",
          tone: "warning",
          title: "Administrator safeguards",
          text: "The final active administrator cannot be disabled, demoted, or deleted. Administrative password resets and permanent deletion require the acting administrator's current password and are written to the audit history.",
        },
      ],
    },
    {
      id: "dashboard",
      title: "Dashboard",
      summary: "Use the overview cards and charts to understand recent activity.",
      roles: allRoles(),
      keywords: ["dashboard", "metrics", "charts", "camera", "time frame", "top plates"],
      blocks: [
        {
          type: "bullets",
          title: "Dashboard controls and metrics",
          items: [
            "Camera limits the dashboard to one configured camera; All cameras combines them.",
            "Time frame changes the period used by total reads, unique vehicles, new vehicles, time distribution, camera counts, and top plates.",
            "Select a time-distribution bar to open Recognition Feed filtered to that hour.",
            "Hover over a top plate to preview recent captures. Select its reads count to open all matching appearances.",
            "The header links open the community documentation, fork source, product roadmap, and this Help Center.",
          ],
        },
        {
          type: "note",
          tone: "info",
          title: "Empty dashboard",
          text: "Waiting for License Plate Data means the application is ready but no accepted reads match the selected camera and time frame. It is not, by itself, a database error.",
        },
      ],
    },
    {
      id: "recognition-feed",
      title: "Recognition Feed",
      summary: "Browse individual reads, filter activity, inspect images, and control live updates.",
      roles: allRoles(),
      keywords: ["live feed", "recognition feed", "filter", "sorting", "live updates", "camera", "confidence"],
      blocks: [
        {
          type: "steps",
          title: "Find a group of reads",
          items: [
            "Open Live Feed and expand Search options.",
            "Enter a complete or partial plate, then choose a Plate matching mode when approximate OCR matching is useful.",
            "Optionally narrow the results by tag, camera, date, or hour.",
            "Select a sortable column heading to switch between ascending and descending order.",
            "Keep Live updates enabled for monitoring. Disable it while reviewing a stable result set so new reads do not move the rows.",
          ],
        },
        {
          type: "bullets",
          title: "Row and image actions",
          items: [
            "Select a thumbnail to inspect the larger capture and read details. When crop coordinates are available, the viewer opens focused on the plate. Scroll the mouse wheel over the image or use the slider to zoom continuously; select Reset to return to the full image.",
            "Select Previous Read or Next read to move through the filtered Live Feed results in either direction. Navigation continues across result pages instead of wrapping. Left Arrow and Right Arrow provide the same review navigation from the keyboard.",
            "The popup remembers the last Plate capture or Vehicle view selection in this browser, including after signing out and back in. Reads without a vehicle image temporarily show the plate capture without changing that saved preference.",
            "Select Confirm and Next to confirm an unreviewed read and, only after confirmation succeeds, advance to the next unconfirmed read. Already confirmed reads are skipped, including across result pages; if no later unconfirmed read can be found, the viewer stops instead of wrapping. Plate corrections preserve the cursor or selection when editing in the middle of the value.",
            "The two popup action rows use aligned fixed-width columns, so review status changes and unavailable optional actions do not move Next read or neighboring controls.",
            "Use Add tag or Remove tag to change classification when your role permits tag management.",
            "Use Confirm detected plate, Correct this read, Reject, Reopen, or Reverse review only after inspecting the original image.",
            "Delete is destructive and appears only for accounts with plate deletion permission.",
          ],
        },
        {
          type: "note",
          tone: "warning",
          title: "Matching is a candidate finder",
          text: "Approximate plate matches are not proof that two sightings are the same vehicle. Confirm the image, camera, time, and original observed OCR before taking action.",
        },
      ],
    },
    {
      id: "plate-matching",
      title: "Plate matching profiles",
      summary: "Choose Off, Strict, Balanced, or Broad without hiding how approximate matching behaves.",
      roles: allRoles(),
      keywords: ["fuzzy", "strict", "balanced", "broad", "ocr", "matching", "search"],
      blocks: [
        {
          type: "bullets",
          title: "Profile guide",
          items: [
            "Off: normal exact or partial text search. MQTT identity rules remain exact.",
            "Strict: favors the lowest false-positive rate and only accepts narrowly defined OCR-equivalent differences.",
            "Balanced: handles common OCR confusion and at most one ordinary difference within configured limits. This is the best starting point for a suspected misread.",
            "Broad: allows a wider candidate set for poor captures. Review the images carefully because false positives increase.",
            "Settings > Plate Matching lets an administrator configure minimum length, OCR-equivalent groups, insertion/deletion behavior, adjacent transpositions, and limits, then test two values interactively.",
          ],
        },
        {
          type: "example",
          title: "Example: search for a likely OCR misread",
          scenario: "The image looks like ABC128, but a prior camera read may have stored ABC123.",
          steps: [
            "Search for ABC128 with Off first to find exact and ordinary partial matches.",
            "If the expected sighting is missing, choose Balanced and search again.",
            "Inspect every candidate's image and timestamp. Use Broad only if Balanced is still too narrow.",
            "If ABC123 is a repeated, confirmed misread, an administrator can create an explicit recurring alias after correction.",
          ],
          result: "The search broadens gradually while the final identity decision remains a human review.",
        },
      ],
    },
    {
      id: "reviews-and-aliases",
      title: "Reviewing, correcting, and recurring aliases",
      summary: "Correct effective identity without destroying what the camera originally observed.",
      roles: ["administrator", "operator"],
      keywords: ["confirm", "correct", "reject", "reverse", "batch", "alias", "observed plate", "history"],
      blocks: [
        {
          type: "paragraph",
          text: "Every read keeps an immutable observed plate from the camera. Reviews change the effective plate used by searches, known-plate data, tags, rules, notifications, and MQTT while preserving the original evidence and append-only history.",
        },
        {
          type: "example",
          title: "Example: correct one read without losing evidence",
          scenario: "The camera reported ABC123, but the image clearly shows ABC128.",
          steps: [
            "Open the capture from Recognition Feed and compare the image with the observed plate.",
            "Select Correct this read and enter ABC128.",
            "Add a concise reason such as Clear final digit in full image and optional notes.",
            "Leave batch correction off unless the preview shows that every selected match is the same mistake.",
            "Apply the correction and open review history to confirm that ABC123 remains the observed plate while ABC128 is effective.",
          ],
          result: "Existing evidence remains immutable, and downstream known-plate, tag, rule, notification, and MQTT behavior uses ABC128.",
        },
        {
          type: "example",
          title: "Example: create a camera-scoped recurring alias",
          scenario: "Driveway West repeatedly reads ABC128 as ABC123, while another camera may legitimately see ABC123.",
          steps: [
            "Correct a verified Driveway West read from ABC123 to ABC128.",
            "Choose Remember as recurring alias and scope the alias to Driveway West.",
            "Preview the source, target, and camera scope before saving.",
            "Open Settings > Review & Corrections to confirm the alias is enabled.",
            "If the rule later proves unsafe, disable it. Aliases are retained for audit and cannot be deleted.",
          ],
          result: "Future exact ABC123 observations from only Driveway West resolve to ABC128; the original observed value and alias application remain auditable.",
        },
        {
          type: "note",
          tone: "warning",
          title: "Batch correction requires preview",
          text: "Batch correction is administrator-only. Review the server-generated scope and count, and never use a broad search result as automatic identity proof. Reverse the latest review when an approved correction must be undone.",
        },
        {
          type: "note",
          tone: "info",
          title: "Repairing an incorrect recurring alias",
          text: "If the read already has the correct effective plate, enable Remember as recurring misread and use Save recurring alias; no batch correction is needed. When an enabled alias conflicts, Replace alias disables the prior mapping and creates the reviewed replacement while retaining both records for audit. Review reversal separately confirms whether its associated active alias should also be disabled.",
        },
      ],
    },
    {
      id: "plate-database",
      title: "Plate Database",
      summary: "Search summarized plate identities, sort every supported field, and carry filters into exports.",
      roles: allRoles(),
      keywords: ["database", "search options", "name", "notes", "tag", "camera", "date", "hour", "sorting"],
      blocks: [
        {
          type: "steps",
          title: "Build a precise database view",
          items: [
            "Open Database and expand Search options.",
            "Search by plate, known name, or notes and choose the matching profile.",
            "Combine the search with tag, camera, date, and hour filters as needed.",
            "Choose a page size and select a column heading to sort by plate, occurrences, name, notes, first seen, last seen, or tags.",
            "Use Clear controls to remove the complete filter set before starting another investigation.",
          ],
        },
        {
          type: "bullets",
          title: "Important behavior",
          items: [
            "Plate Database summarizes effective plate identities; Recognition Feed shows individual read events.",
            "Blank optional values sort last in both directions so missing names or notes do not hide populated rows.",
            "View insights opens aggregate details for the selected plate.",
            "Export these results preserves the current filters, matching mode, and sorting on the Downloads page when your role permits exports.",
          ],
        },
      ],
    },
    {
      id: "known-plates-tags-watchlist",
      title: "Known Plates, tags, and Monitored Plates",
      summary: "Attach human context to plate identities and manage focused monitoring safely.",
      roles: ["administrator", "operator", "viewer", "auditor"],
      keywords: ["known plates", "tags", "watchlist", "flagged", "name", "notes"],
      blocks: [
        {
          type: "bullets",
          title: "Known Plates",
          items: [
            "Known Plates can store a name and notes for a plate identity and display its tags.",
            "Select a license plate value to open Live Feed with exact matching and review its individual reads.",
            "Select any supported column heading to sort. Sorting is stable, numeric-aware, case-insensitive, and keeps blank optional values last.",
            "Administrators and Operators can edit known-plate details and tags. Viewers and Auditors can read them without mutation controls.",
            "Plate identifiers use a slashed zero wherever the active font supports the OpenType slashed-zero glyph, helping distinguish 0 from O.",
          ],
        },
        {
          type: "bullets",
          title: "Tags and Monitored Plates",
          items: [
            "Use tags for reusable classifications such as family, delivery, service, or vehicle color. A tag can appear in search and MQTT matching.",
            "Monitored Plates replaces the separate Watchlist page and is available as a view inside Known Plates. Existing flagged-plate data remains compatible with rule evaluation.",
            "For each monitored plate, record a reason, choose low, normal, high, or critical priority, and review monitoring-since, last-seen, read-count, tag, and exact-history context.",
            "A unified rule with the monitored-plate condition decides which cameras and delivery channels act on a monitored read. Priority is operator context and does not enable delivery by itself.",
            "Before removing a tag, consider how it affects saved searches, MQTT rules, and operational habits.",
          ],
        },
      ],
    },
    {
      id: "push-notifications",
      title: "Notification rules and delivery channels",
      summary: "Configure each delivery integration separately, then build, preview, activate, and troubleshoot notification rules from a focused workspace.",
      roles: ["administrator"],
      keywords: ["notification", "pushover", "email", "smtp", "webhook", "signature", "priority", "test", "alert"],
      blocks: [
        {
          type: "steps",
          title: "Create a unified notification rule",
          items: [
            "Open the needed service directly under Settings > Integrations. MQTT, Pushover, Email, and Webhook each have a dedicated tabbed setup page; there is no separate Integrations overview page. Never include credentials or secrets in screenshots or support messages.",
            "For email, open Settings > Integrations > Email. Use the SMTP Connection, Sender Identity, and Test tabs to configure and verify delivery. Keep certificate verification enabled unless you fully control and trust the relay.",
            "For webhooks, open Settings > Integrations > Webhook. Use Signing & Delivery, Network Safety, and Test. Prefer HTTPS; HTTP and private-network targets require explicit permission, while loopback, link-local, special-use targets, URL credentials, redirects, and fragments remain blocked.",
            "For Pushover, open Settings > Integrations > Pushover. Connection holds enablement and credentials, Defaults controls presentation, Usage shows the monthly allowance and remaining messages, and Test sends a direct alert. Select Refresh usage after changing the application token or sending a test.",
            "Open Notification Rules from the left sidebar. On the Rules tab, select Create rule and enter a name, optional description, cooldown in seconds, and the explicit rule time zone. Every new draft resolves the browser-local time zone when Create rule is selected; quiet hours and new Schedule conditions inherit that rule time zone. Unified rules preserved by a completed legacy finalization or retirement appear in this normal Rules list.",
            "Choose Accepted plate read for an arrival rule. Choose Scheduled camera activity to detect no or fewer than a configured number of camera reads within a period; select the camera, use a camera-scoped Read count condition, and choose how often the server checks it.",
            "Choose whether each group requires All (AND), Any (OR), or Not. Add nested groups as needed, up to six levels deep. Conditions can match any accepted read, a plate, a known plate, a tag, a Monitored Plate, one or more cameras, confidence, read counts, or a local weekday/time schedule.",
            "Tag and Known plate are independent conditions. A Tag condition matches the effective plate's assigned tags even when that plate is not in Known Plates; add a separate Known plate condition only when both facts are required.",
            "Plate matching supports the shared fuzzy profiles plus explicit exact, contains, wildcard (* and ?), OCR-confusion-only, and bounded edit-distance strategies.",
            "For Read count, select the same plate, same camera, or all reads; choose the comparison and count; then select Lifetime or enter a period in minutes, hours, or days. Counts are evaluated at each read's persisted event time, including that read.",
            "Add one or more actions. MQTT uses an existing broker and a per-camera or fixed topic. Pushover can specify priority and a message. Email specifies up to 10 recipients, an optional subject/message, and whether to attach the capture. Webhook specifies a target URL and optional message. Credentials remain protected in Settings rather than being copied into rules.",
            "Optionally enable Quiet hours, enter the local start/end times, choose weekdays, and verify the time zone. A matched event during quiet hours is recorded as suppressed and does not queue delivery.",
            "Select Save disabled draft. Saving or editing cannot enable the rule and makes no delivery attempt.",
            "Select Preview to evaluate the saved version against up to 25 recent real reads. Review matched and non-matched rows and expand any row to inspect its complete condition trace; the preview always reports zero delivery attempts.",
            "When the result is correct and every selected channel is ready, select Activate and confirm the separate prompt. Activation enables the rule, channel, and actions atomically and records an audit event.",
            "Select Deactivate to pause all actions atomically. An active rule must be deactivated before it can be edited, and every saved edit increments its version.",
            "To remove a rule, deactivate it first and then select Delete. Confirm the exact rule name and version in the popup. The rule immediately disappears from Notification Rules and can never evaluate or deliver again; historical activity and audit references remain available.",
            "Open the Activity & delivery tab to review each recent decision, its event-time trace, suppression reason, channel delivery state, retry attempts, and dead-letter error. MQTT, Pushover, email, and webhook delivery failures are handled asynchronously without holding open plate ingestion.",
          ],
        },
        {
          type: "note",
          tone: "warning",
          title: "Rules use guarded activation",
          text: "Rules use disabled drafts, no-delivery preview, separate audited activation, atomic deactivation, and protected credential references. Unified MQTT, Pushover, email, and webhook actions use durable, deduplicated delivery ledgers with bounded retries and dead-letter state. Webhook receivers should verify the HMAC-SHA256 X-ALPR-Signature against the raw JSON body and deduplicate with Idempotency-Key.",
        },
      ],
    },
    {
      id: "mqtt",
      title: "MQTT integration",
      summary: "Connect brokers, map cameras and topics, and test MQTT delivery while managing all automation from Notification Rules.",
      roles: ["administrator"],
      keywords: ["mqtt", "broker", "rule", "topic", "camera", "outbox", "test"],
      blocks: [
        {
          type: "steps",
          title: "Safely configure MQTT",
          items: [
            "Open Settings > Integrations > MQTT and add the broker connection first. The former /mqtt address redirects here. Use a dedicated, least-privilege broker account when possible.",
            "Test the broker connection before creating a rule in Notification Rules. A successful broker test proves connectivity, not that a rule is correct.",
            "Review detected camera mappings and the per-camera topic before enabling automation.",
            "Open Notification Rules and create a disabled rule. Add an MQTT action, select its broker and destination, and configure the trigger and conditions there.",
            "Review the rule summary, preview recent matches, then activate it during a supervised test window and check MQTT activity for delivery or retry status.",
            "Expand Payload and attempts in Delivery Activity to confirm the plate, matched rule, runtime, attempt count, and final outcome without exposing broker credentials.",
          ],
        },
        {
          type: "example",
          title: "Example: publish a delivery tag",
          scenario: "Home automation should receive accepted reads tagged Delivery from the driveway camera.",
          steps: [
            "Confirm the Delivery tag exists and is assigned consistently.",
            "Create a unified rule on Notifications with a Tag condition whose value is Delivery and add an MQTT action.",
            "Add a driveway Camera condition and select the intended broker in the MQTT action.",
            "Choose the exact fixed topic or verify the per-camera destination preview.",
            "Leave plate matching Off because tag matching does not need approximate plate identity.",
            "Save disabled, review it, then enable and observe one controlled test read.",
          ],
          result: "Only accepted driveway reads carrying the Delivery tag enter the durable MQTT delivery flow.",
        },
        {
          type: "note",
          tone: "warning",
          title: "Avoid automation loops",
          text: "Do not publish to a topic that another integration converts back into the same ALPR input. Keep test topics separate from production automation and verify retained-message behavior on the broker.",
        },
      ],
    },
    {
      id: "exports",
      title: "Downloads and exports",
      summary: "Download bounded CSV or JSON results using the same filters as Plate Database.",
      roles: ["administrator", "auditor"],
      keywords: ["download", "export", "csv", "json", "filter", "spreadsheet"],
      blocks: [
        {
          type: "example",
          title: "Example: export the exact filtered investigation",
          scenario: "You need all Balanced matches for ABC128 from Driveway West during the previous week, sorted newest first.",
          steps: [
            "Build the view in Plate Database: search ABC128, choose Balanced, select Driveway West, set the date range, and sort Last seen descending.",
            "Select Export these results. Downloads opens with the same search, matching mode, camera, dates, and sorting.",
            "Confirm every filter before downloading.",
            "Choose CSV for spreadsheet analysis or JSON for structured processing.",
          ],
          result: "The export contains up to 50,000 matching database records and reports when the result was truncated.",
        },
        {
          type: "bullets",
          title: "Export safety",
          items: [
            "CSV fields are escaped and spreadsheet-formula prefixes in user-controlled text are neutralized.",
            "Exports contain database text and timestamps, not a ZIP of capture images.",
            "Treat exported plate activity as sensitive data. Store it only where authorized and remove copies when they are no longer needed.",
          ],
        },
      ],
    },
    {
      id: "blue-iris-recordings",
      title: "Blue Iris continuous recordings",
      summary: "Connect to Blue Iris read-only and verify that plate-read times can be correlated with alerts in continuous BVR recordings.",
      roles: ["administrator"],
      keywords: ["blue iris", "bvr", "continuous recording", "alert", "clip", "drivepool"],
      blocks: [
        {
          type: "steps",
          title: "Configure safe alert correlation",
          items: [
            "Create a dedicated Blue Iris account that can view the LPR cameras, alerts, and clips but cannot administer Blue Iris or delete recordings.",
            "Open Settings > Blue Iris. Enter the Blue Iris HTTP or HTTPS server address and optional port, username, password, and request timeout, then select Save Changes.",
            "Select Test connection. The result lists the camera identifiers returned by Blue Iris without exposing the saved password.",
            "Choose a camera and enter the local timestamp of a known plate read, then select Find matching alert. Start with a 90-second tolerance and narrow it after camera identifiers and clocks are verified.",
            "Open Settings > Vehicle Setup > Vehicle Views. Under Daytime overview association, add one camera-pair row for each validated direction. Use Street Overview as the primary source. Enter Overview time minus plate-read time as the expected delta: Street LPR 1 is normally close to one second and Street LPR 2 is normally four to five seconds apart, but measure the installed cameras and choose a tolerance that covers ordinary variation without overlapping nearby vehicles.",
            "Add Entry LPR 1 and Entry LPR 2 as driveway fallback sources for the directions in which a vehicle may turn before Street Overview sees it. Once a plate camera is configured as a fallback source, its existing authenticated plate alert also creates the independent clip candidate; no camera clone or second Entry-camera action is required.",
            "On Street Overview, add an authenticated Blue Iris web-request action to /api/vehicle-overview-candidates with the alert JPEG, camera name, alert path, alert clip, timestamp, and optional &TYPE. The exact JSON appears on the Vehicle Views setup page. Street Overview does not need to read a plate.",
            "Every color daytime candidate is screened for a vehicle. The worker samples a bounded six-second interval from 0.5 seconds before through 5.5 seconds after the motion time at 100-millisecond intervals and retains only the best complete, sharp JPEG. Non-vehicle triggers become unavailable without being assigned to a read. Monochrome alerts are recorded only as Unavailable nighttime and never enter frame selection or association.",
            "After all expected plate reads have had time to arrive, ALPR uses the configured camera pair, validated Blue Iris direction, measured timing delta, and conservative ambiguity margin. Matching Street LPR 1 and 2 observations of the same plate may share the same overview candidate. Nearby competing vehicles remain unassigned instead of receiving a guessed image. Driveway fallbacks wait longer for late Entry LPR reads.",
            "New daytime plate reads wait for this overview association and no longer sample their Street LPR plate camera for a normal live Vehicle View. A nighttime plate read immediately displays Unavailable nighttime. Historical and deliberate manual recovery controls retain the older plate-camera selector without changing the new live workflow.",
            "Open Settings > Vehicle Setup > Vehicle Views to queue missing historical vehicle views for one camera or all cameras, optionally expand the date-range controls, and pause or resume only historical work. Queueing always leaves history paused until Resume history is selected. Cancel pending history safely removes pending or retryable historical jobs for the selected camera and optional date range while preserving completed images, live work, and manual retries.",
            "Use the Vehicle Views status panel to verify the live worker state, live backlog, and last worker error. This makes stalled or unhealthy processing visible without opening server logs.",
            "New incoming reads preserve the Blue Iris clip, alert path, and offset metadata supplied by the existing Blue Iris action. Historical reads can be matched by camera and timestamp through Blue Iris alertlist metadata.",
            "For LPR direction setup, open Settings > Vehicle Setup > Cameras, select the camera, and map two exact reverse Blue Iris trigger values such as MOTION_A>B and MOTION_B>A to the existing semantic direction labels. Enable Blue Iris zone-crossing direction only after both mappings have been verified with live traffic.",
            "In Blue Iris, preserve the existing plate alert and use explicit ordered zone rules such as A>B,B>A rather than the bidirectional shorthand A-B. Add \"trigger_type\":\"&TYPE\" to the existing JSON web-request payload. The plate, camera, alert pointer, timestamp, and ordered crossing then arrive in one authenticated request.",
            "Review the selected camera's received, mapped, unknown, and unmapped totals under Vehicle Setup. For new daytime reads received after this release, a mapped Blue Iris crossing supplies the displayed direction and direction notification event immediately. Missing, disabled, shorthand, and unmapped crossings fall back to the existing single-frame Vehicle ReID result. Monochrome nighttime captures bypass both sources, display Unavailable nighttime, and do not send direction notifications. Existing historical directions and legacy shadow observations are not rewritten or backfilled.",
            "Open the read in Recognition Feed and use Plate capture or Vehicle view to switch between the immutable ALPR image and the derived Blue Iris overview image. While association is pending, the overlay says Waiting for daytime overview. A nighttime read says Unavailable nighttime. No-match, ambiguity, and legacy plate-camera outcomes use separate plain-language messages.",
            "Retry vehicle view appears only for an older manual or historical operation whose failure can benefit from another attempt. It is hidden for nighttime reads and other terminal overview outcomes, where retrying the plate-camera window would not help.",
          ],
        },
        {
          type: "note",
          tone: "info",
          title: "Recordings stay in Blue Iris",
          text: "ALPR never mounts DrivePool volumes, parses BVR files, changes retention, or deletes recordings. Overview selection uses Blue Iris's read-only timeline JPEG endpoint and retains only one candidate JPEG until association, then one read-owned JPEG for each matched read. Rejected samples and videos are not retained. Candidate images remain protected from storage cleanup while queued. The former dense clip vehicle-direction experiment remains removed: direction uses only the ordered trigger metadata Blue Iris already calculated, while the new 100-millisecond sampling is limited to selecting a daytime overview still image.",
        },
      ],
    },
    {
      id: "settings-audit-privacy",
      title: "Settings, users, audit, and privacy",
      summary: "Understand personal settings, administrative controls, audit history, and local-only privacy behavior.",
      roles: allRoles(),
      keywords: ["settings", "user management", "audit", "logs", "privacy", "retention", "password"],
      blocks: [
        {
          type: "bullets",
          title: "Settings and administration",
          items: [
            "Every named user can change their own password from personal settings.",
            "Administrators can manage users, system settings, integrations, plate matching profiles, and recurring aliases when the related permission is present.",
            "System Logs is available to Administrators and Auditors and includes durable security/audit events in addition to application logs.",
            "Data & Privacy is local status and configuration. Upstream telemetry, AI-training uploads, and remote update polling have been removed from this fork.",
          ],
        },
        {
          type: "note",
          tone: "info",
          title: "Audit history is intentionally durable",
          text: "Security, user-management, and review events are retained to explain who changed what and when. Deleting a user scrubs the login identity while retaining an audit tombstone rather than erasing history.",
        },
      ],
    },
    {
      id: "maintenance-updates",
      title: "Maintenance, backups, and updates",
      summary: "Use the established deployment process without exposing unrestricted host control inside the website.",
      roles: ["administrator"],
      keywords: ["maintenance", "backup", "update", "migration", "restore", "health", "rollback"],
      blocks: [
        {
          type: "bullets",
          title: "Read storage health safely",
          items: [
            "Administrators can open Settings > Data & Privacy and use the Storage Health, Monitoring, Cleanup, and Privacy tabs. Each tab has a clean address that can be bookmarked or restored with browser navigation.",
            "Storage Health contains capacity, category, database, capture, visual-index, projection, and read-only PostgreSQL statistics. Monitoring contains thresholds, scheduler liveness, reconciliation, and alert destinations. Cleanup contains derived-orphan and host-retention controls. Privacy contains the local-only reporting and explicit-integration policy.",
            "Mounted filesystem capacity and PostgreSQL size are direct measurements. Completed reconciliation provides exact source-image, thumbnail, and derived-file counts and bytes. Docker and backup totals appear only from a current read-only host snapshot and otherwise remain clearly unavailable.",
            "Reads/day uses the last seven days. Estimated bytes/read samples at most 120 recent source, thumbnail, and derived files; it does not recursively scan the storage tree.",
            "Capacity dates are planning estimates, not promises. Logs, backups, database overhead, and other files sharing the mount can move the dates. Warning and critical thresholds control health state and alerts.",
            "Index-confirmed missing sources counts current failed visual assets with SOURCE_IMAGE_MISSING. Reads without an image path are reported separately.",
            "Retention and record-limit planning runs in a scheduled single-flight worker instead of plate ingestion. Its results remain dry-run previews based on database references and never delete rows or files.",
            "Read-only storage reconciliation walks only images, thumbnails, and derived storage roots in bounded resumable batches. It records exact orphaned-file and missing-reference paths, totals, sizes, progress, and a review sample without deleting anything.",
            "Files created after a reconciliation starts are deferred to the next run. Symlinks, invalid paths, and access errors are skipped and reported rather than classified as cleanup candidates.",
            "Run preview now refreshes maintenance evidence without deletion. Manual cleanup is a separate typed-confirmation action limited to generated derived files that remain unreferenced after fresh database, real-path, symlink, size, and modification-time checks.",
            "Automatic cleanup defaults to disabled and uses a separate Administrator-only, typed, actor-recorded approval. The sole supported category is reconciliation-confirmed generated derived orphans. Each run requires the latest reconciliation to be completed, fresh, and error-free; candidate mtimes must predate both the scan start and the seven-day grace cutoff.",
            "An automatic run handles at most 100 files or 1 GiB and admits new candidates for at most five minutes, without catch-up loops. Per-candidate database lock and statement waits use the remaining scheduling budget; a filesystem operation already in progress is allowed to finish safely. It rechecks the current approval revision between files and uses the same five-column reference, advisory/writer lock, table lock, real-path, symlink, hard-link, size, mtime, device, and inode safeguards as manual cleanup. A failure suspends automation, makes reconciliation due, and requires a newer successful reconciliation plus typed Administrator acknowledgement.",
            "Host artifact retention has three independent boundaries: Docker build cache, unused ALPR and maintenance-worker images, and verified rollout backups. Preview candidates and opaque tokens come only from a separately installed fixed host worker; the browser never supplies a path, image ID, backup ID, or command.",
            "While a host-maintenance preview or cleanup is pending or processing, the Cleanup page follows its status automatically, updates both the request card and summary metrics from the same request, and preserves the active request across a server refresh. Pending previews say Calculating instead of presenting zero as a result, and the preview button remains disabled until that category finishes; the server also serializes category requests to prevent duplicate queue entries. The normal view has no manual status button; Retry status update appears only if automatic updates pause after repeated interruptions.",
            "Administrators can request one manual PostgreSQL custom-format database backup from the Cleanup page only when the fixed worker explicitly advertises database-backup-create-v1. The browser supplies no path, filename, database name, command, arguments, schedule, or restore input. The fixed operation has a 50 GiB output ceiling. While a request is pending or processing, the page refreshes its status automatically and stops polling at completion or failure. It reports the last status, time, basename, verified size, and a sanitized error; checksums and protected operational details remain outside browser state.",
            "The database-backup button remains disabled when that exact worker capability is absent or stale. Shipping the application control plane alone does not install the reviewed fixed adapter, runtime tooling, approved backup-root implementation, or verification receipt. The reviewed worker is active and capability-validated on staging and production. On August 2, the first authorized production request completed once and verified alpr-postgres-20260802T164636Z-1.dump at 61.8 MB with no reported error. The worker role has only narrow access to the dedicated request queue; the fixed host adapter performs the dump against the exact database container.",
            "All host schedules default off. Docker cache and backup retention require different one-time activation phrases. Unused-image scheduling is unsupported, and backup cleanup never deletes images. The manual image-retirement grace defaults to seven days and can be changed from one to 365 days only with Administrator approval and the displayed typed phrase. Application and maintenance-worker images use separate append-only ledgers, and the current attested worker is protected. A reviewed worker may adopt only exact, verifiable legacy identities where rollback references are fully accounted for; unknown production application images remain protected and block preview. If the worker is not installed or its heartbeat is stale, the controls fail closed and a rate-limited maintenance alert is raised when scheduled work depends on it.",
            "Backup retention always protects the newest five verified backups and every verified backup newer than 30 days, plus current and rollback chains. The worker rejects partial, corrupt, foreign, manifestless, symbolic-link, hard-link, or identity-drifted backups. Current/prepared releases, the exactly attested current maintenance worker, database data, captures, volumes, container references, leases, and unknown images remain protected. An environment-specific worker installation may append exact pre-control-plane identities as retired metadata only when immutable labels match and rollback references are fully accounted for; production leaves unknown application images protected. Adoption deletes nothing and starts the configured grace.",
            "An unused-image preview reports the logical size of eligible image identities for cap enforcement; it is not a promise of filesystem space. After each exact deletion, the locked worker measures Docker's layer-store size before and after the operation and reports only the conservative Docker-accounted decrease, capped by that candidate's logical size. Shared layers can therefore make actual reported reclaim smaller than the preview, including zero.",
            "PostgreSQL maintenance information is observational only: the page reports database/table tuple statistics, recent autovacuum/autoanalyze activity, tables with material dead-tuple ratios, and transaction-ID age. It does not execute VACUUM or ANALYZE.",
            "Source images, thumbnails, database rows, referenced captures, Docker volumes, containers, networks, current or prepared releases, and protected rollback backups have no deletion action in this workflow. When the fixed host worker is installed, only preview-confirmed category candidates can be requested. Manual database-backup creation is a separate fixed operation, while restore preflight and restore execution remain external operations.",
            "Users without maintenance management permission can inspect this status but cannot delete or modify images.",
            "Maintenance email and signed-webhook alerts use durable retries and a per-event cooldown. Test email uses the saved SMTP configuration and the recipients currently entered on the page without saving the policy, and shows its result inside the Email alerts card. The maintenance webhook destination is write-only: the page reports only whether one is configured and provides separate Replace, Test, and Clear controls with results inside the Webhook alerts card. Ordinary policy saves preserve the saved destination. Queued alerts resolve the current destination immediately before each send; clearing it retires unsent webhook deliveries so an old URL is not retried. A request already in flight during Replace or Clear may still finish at the prior destination. Warning-to-critical escalation and recovery are not hidden by repeat-warning rate limiting. A stale heartbeat can detect a stopped maintenance loop while the app is alive; whole-app or host outages still require an external uptime monitor.",
          ],
        },
        {
          type: "bullets",
          title: "Safe release process",
          items: [
            "Administrators can read installed release information under Settings > Release, including the application version, deployment-provided Git SHA, release channel, and local release notes.",
            "Commit-pinned Docker builds embed their exact checked-out SHA and branch channel without retaining Git history in the runtime image. ALPR_RELEASE_SHA and ALPR_RELEASE_CHANNEL remain explicit deployment overrides; no network lookup or mutable-state guess is used.",
            "Changes are tested on a feature branch, validated by tests/typecheck/lint/build/security checks, and deployed to isolated staging first.",
            "Production deployment requires explicit approval, a verified PostgreSQL backup, an exact commit/image, one migration run, app-only restart when possible, health checks, and bounded log review.",
            "Every production candidate updates this help manual and the product roadmap in the same release so current behavior and remaining work stay aligned with production.",
            "Application rollback returns to the recorded previous image. A runtime rollback does not automatically reverse database migrations.",
            "The website does not provide an arbitrary SQL shell, host shell, or unrestricted Docker update button.",
          ],
        },
        {
          type: "note",
          tone: "warning",
          title: "Legacy migration pages",
          text: "Backfill, JPEG migration, and Update pages are specialized maintenance tools, not routine navigation. Use them only with a current backup and a release-specific procedure.",
        },
      ],
    },
    {
      id: "troubleshooting",
      title: "Troubleshooting",
      summary: "Collect useful evidence without exposing credentials or changing data unnecessarily.",
      roles: allRoles(),
      keywords: ["troubleshooting", "error", "health", "support", "browser", "logs"],
      blocks: [
        {
          type: "steps",
          title: "When a page does not behave as expected",
          items: [
            "Confirm the signed-in username and role, then decide whether the behavior is a permission boundary or an application failure.",
            "Reload once and reproduce the smallest failing action. Record the page, time, selected filters, and exact visible error.",
            "Check the health endpoint or ask an Administrator to review System Logs and the bounded container logs for the same time.",
            "Capture a screenshot only after checking that it contains no password, session, API key, broker secret, private plate image, or unnecessary personal data.",
            "Do not refresh datasets, prune Docker, edit database rows, rerun migrations, or redeploy repeatedly merely to see whether the problem disappears.",
          ],
        },
        {
          type: "bullets",
          title: "Useful problem report",
          items: [
            "Application release or commit, browser/device, signed-in role, page, local timestamp, expected result, actual result, and reproduction steps.",
            "Whether the failure affects one account, one camera, one plate, or all activity.",
            "Whether a recent configuration, migration, or deployment preceded the problem.",
          ],
        },
      ],
    },
    {
      id: "visual-search",
      title: "Visual vehicle search",
      summary: "Compare local derived vehicle crops while keeping original captures unchanged.",
      roles: allRoles(),
      keywords: ["visual search", "vehicle image similarity search", "vehicle crop", "vehicle reid", "openvino", "duplicate", "camera filter"],
      blocks: [
        {
          type: "steps",
          title: "Find captures that look similar",
          items: [
            "Open a capture from Recognition Feed or Plate Database, then choose Find similar vehicle. You can also choose a recent indexed capture or upload a JPEG, PNG, or WebP vehicle image up to 5 MB in Visual Search.",
            "Uploaded queries are validated, decoded, and compared transiently. They are not stored as plate reads or written to the image library.",
            "Optionally narrow results by one or more cameras and a date range, then apply the filters.",
            "Review Vehicle ReID candidates visually. The learned image-embedding score is independent of plate text; the displayed plate is only a link to supporting capture history.",
            "Administrators and Operators can label a stored-source result Same vehicle or Different vehicle. Select the other choice later to correct a label; every change is retained in the audit history.",
            "Use Plate details to inspect the candidate's exact plate history and full capture context.",
          ],
        },
        {
          type: "bullets",
          title: "Index and score behavior",
          items: [
            "A resumable background worker indexes the newest unindexed captures automatically without making ingestion wait. Administrators can select a gentle, balanced, or fast pace, pause or resume the worker, and run one batch immediately.",
            "Automatic indexing pauses before a batch when free storage or system load crosses its configured safety threshold, then retries after the system recovers.",
            "OpenVINO scans the complete capture first, detects and tightly crops the vehicle, then vehicle-reid-0001 stores a normalized 512-value descriptor. A SHA-256 source hash separately identifies byte-for-byte duplicate captures.",
            "Automatic vehicle detection reports success and fallback counts per camera. It recommends review only after a meaningful sample shows recurring detector misses.",
            "Advanced camera fallback settings remain collapsed during normal use. Full image is the default; plate-centered adaptive or custom framing is used only when the detector cannot isolate a vehicle.",
            "Saving a fallback profile creates a new profile revision and reindexes only that camera's next 20 captures. Original capture images are never changed.",
            "Plate values never affect result inclusion, score, order, or labels. They are displayed only so a person can inspect the candidate's plate history.",
            "Search compares cosine similarity across at most 5,000 recent filtered indexed captures. Percentages rank candidates; only Exact duplicate is an identity claim.",
            "Match calibration summarizes local same/different labels for the current embedding model. Its candidate threshold is analysis only and never changes ranking or identity labels automatically.",
          ],
        },
        {
          type: "steps",
          title: "Configure vehicle direction by camera",
          items: [
            "Administrators open Settings > Vehicle Setup. Use the route-backed Cameras, Vehicle Views, Processing, and Calibration tabs to work on one task at a time. The main Vehicle Intelligence workspace remains dedicated to profiles and review work. Each camera-specific setup page shows its own camera selector; camera names and direction meanings are never built into the application. On desktop, the Settings sidebar can collapse to an icon rail without changing the current page.",
            "Enter what a visible vehicle front means for that camera and what a visible rear means. These may be compass directions such as Eastbound and Westbound or site meanings such as Entering driveway and Exiting driveway.",
            "Enter the exact reverse Blue Iris zone crossings for those two meanings and enable zone-crossing direction after live verification. New daytime mapped crossings are authoritative; Vehicle ReID is retained for reads where the crossing is unavailable or unmapped. Monochrome nighttime captures are not classified.",
            "Choose a minimum confidence. Results below it remain Unknown instead of being forced into a direction.",
            "Label at least three clear front views and three clear rear views from that camera. Add more examples covering ordinary light, weather, distance, and vehicle shapes to improve local calibration.",
            "Save the camera setup. Recent indexed captures are reevaluated immediately, and the remaining historical reads are queued for the paced background worker.",
            "Historical image-backed reads are evaluated automatically after Vehicle ReID indexing. This page shows assigned, Unknown, pending, and failed totals and lets an administrator run one bounded batch immediately.",
            "After adding or changing calibration examples, use Re-evaluate selected camera or Re-evaluate all cameras to preview the affected counts and queue completed machine-generated results for another pass. Current direction assignments stay visible until their replacements are ready, and human front/rear reviews are preserved.",
            "Use Pause re-evaluation to stop historical rechecks after the current bounded batch, and Resume re-evaluation to continue later. Newly ingested reads remain prioritized and continue receiving direction analysis while historical work is paused.",
            "A new daytime mapped Blue Iris crossing displays its direction immediately. A fallback ReID read displays Pending until analysis finishes; Unknown means fallback analysis completed without enough confidence. A monochrome nighttime read displays Unavailable nighttime. Live Feed refreshes these results while Live Updates is enabled.",
            "The historical process resumes from durable queue state after a restart, retries an individual failure up to three times, preserves human front/rear reviews, and never sends historical direction notifications.",
          ],
        },
        {
          type: "steps",
          title: "Configure daytime Vehicle Views",
          items: [
            "Open Settings > Vehicle Setup > Vehicle Views and configure Street Overview as the primary source for each Street LPR camera and validated daytime direction.",
            "Enter the measured signed timing delta and a bounded tolerance for each camera pair. A lower priority number wins when otherwise comparable source profiles overlap.",
            "Configure Entry LPR 1 and Entry LPR 2 as fallback sources only for driveway-turn cases. Their existing accepted plate alert creates the fallback candidate automatically after the read commits.",
            "Copy the displayed JSON into a separate authenticated Street Overview motion action. Motion without a plate is expected; local vehicle detection screens it before association.",
            "Watch the candidate counters for queued, awaiting plates, associated, ambiguous, unavailable, nighttime skipped, and failed outcomes. Tune timing from evidence rather than widening every tolerance.",
            "Verify daytime examples in Recognition Feed. Nighttime plate reads and monochrome overview alerts display Unavailable nighttime and do not run Vehicle View frame analysis.",
          ],
        },
        {
          type: "note",
          tone: "warning",
          title: "Direction source and fallback",
          text: "Validated Blue Iris ordered zone crossings are authoritative for new daytime mapped reads. Single-frame Vehicle ReID remains a conservative fallback when Blue Iris does not supply a usable crossing; it stores no video clips and leaves uncertain daytime captures Unknown. Monochrome nighttime captures display Unavailable nighttime and are not classified. Historical reads and legacy shadow evidence are not reinterpreted when primary direction is enabled.",
        },
        {
          type: "steps",
          title: "Review vehicle profiles and plate associations",
          items: [
            "Open Visual Search > Needs Review. This top navigation tab keeps outstanding decisions separate from the Vehicle Profiles list.",
            "Administrators can analyze the next bounded batch of unassigned indexed captures. The grouping score uses only Vehicle ReID descriptors; plate text is excluded.",
            "Compare each new capture with the cluster representative. Choose Confirm vehicle when they show the same vehicle, or Different vehicle to move the capture into a separate shadow cluster.",
            "Compare the profile representative with the plate evidence in the Plate associations queue. Confirm association creates the trusted baseline, while Reject association preserves the ReID profile and records the rejection.",
            "For Direction reviews, inspect the complete capture and choose Front view or Rear view. The reviewed example is added to that camera's calibration and the displayed direction is recalculated from the camera setup.",
            "Choose Vehicle Matches, Plate Associations, Directions, or administrator Setup Attention. Only the selected queue is displayed, and its count covers the full database rather than only the current page.",
            "Each review queue has its own Previous and Next controls, so completing or paging one queue does not move the others.",
            "The Vehicle profiles list shows 50 profiles per page. Use its status, camera, and search filters to narrow the list, then use the independent profile pagination controls to inspect all matches beyond the first 100.",
            "Administrators also see Camera setup needs attention when direction meanings, training examples, or detector fallback settings need work.",
            "Shadow means the ReID grouping is a candidate for review, not a vehicle ownership or plate-mismatch claim.",
            "The Recognition Feed image popup shows a Vehicle number, assignment state, ReID score, per-read color and coarse vehicle-type estimates, and direction when available. Type inference runs locally and automatically; low-confidence results remain Unknown.",
          ],
        },
        {
          type: "note",
          tone: "warning",
          title: "Mismatch alerts remain disabled",
          text: "Confirmed plate associations establish an auditable baseline, but profiles do not yet send mismatch notifications or label a plate as switched or stolen. Automated mismatch rules remain a later calibrated phase with minimum evidence and confidence safeguards.",
        },
        {
          type: "note",
          tone: "warning",
          title: "Visual similarity is not identity",
          text: "Two similar-looking vehicles may be different, and one vehicle may look different across angle, light, weather, or camera. Confirm the original images and surrounding evidence.",
        },
      ],
    },
    {
      id: "planned-features",
      title: "Planned features that are not available yet",
      summary: "Avoid confusing roadmap ideas with current production behavior.",
      roles: allRoles(),
      keywords: ["roadmap", "planned", "vehicle ai", "image search", "overlay", "advanced notifications", "storage"],
      blocks: [
        {
          type: "bullets",
          title: "Planned, not current",
          items: [
            "Additional notification conditions such as rarity, site/direction, and vehicle attributes.",
            "Vehicle make, model, and year enrichment with confidence and model/provider provenance. Coarse car, van, truck, or bus type is already automatic and local.",
            "Expanded camera-pair Vehicle ReID calibration and optional make, model, color, coarse type, and year filters.",
            "Controlled VACUUM ANALYZE, backup catalog integration, restore preflight and execution, automatic backup scheduling, and broader backup-verification jobs.",
            "Configurable image overlays rendered non-destructively at view or export time.",
            "Background capture-image ZIP exports and richer release history beyond the installed read-only release summary.",
          ],
        },
        {
          type: "note",
          tone: "info",
          title: "Roadmap status",
          text: "A roadmap entry explains intended architecture; it does not mean the feature is installed. This section will shrink as features pass staging acceptance and reach production.",
        },
      ],
    },
  ],
});

export function manualSearchText(section) {
  const values = [section.title, section.summary, ...(section.keywords || [])];
  for (const block of section.blocks || []) {
    values.push(block.title, block.text, block.scenario, block.result);
    values.push(...(block.items || []), ...(block.steps || []));
  }
  return values.filter(Boolean).join(" ").toLowerCase();
}
