export const HELP_ROLE_LABELS = Object.freeze({
  administrator: "Administrator",
  operator: "Operator",
  viewer: "Viewer",
  auditor: "Auditor",
});

export const HELP_ALL_ROLES = Object.freeze(Object.keys(HELP_ROLE_LABELS));

const allRoles = () => [...HELP_ALL_ROLES];

export const HELP_MANUAL = Object.freeze({
  title: "ALPR Database Community User Guide",
  shortTitle: "User Guide",
  description:
    "A practical guide to viewing plate activity, reviewing OCR results, managing known plates, exporting records, and safely administering your ALPR installation.",
  manualVersion: "1.93",
  updatedAt: "August 14, 2026",
  coverageBaseline: "August 14, 2026 operator-controlled canonical Overview vehicle crops with exact source and detection-box preview, immutable content-addressed JPEG derivatives, explicit 1/5/25/250 canary batches, physical-byte storage projection, cleanup/reconciliation protection, and no current ReID, event, attribute, notification, or Plate Recognizer behavior change; August 14, 2026 default-off provider-neutral shadow vehicle-event correlation for conservative two-read canonical Overview pairs, with exact current-link revalidation, shared-asset preference, bounded Entry/Street timing, fail-closed direction and ambiguity handling, stale-event retirement, and no ingestion, Vehicle View, ReID, notification, or Plate Recognizer effect; August 14, 2026 default-off automatic local cataloging for newly ready Overview images after a completed operator campaign, with a durable bounded queue, exact current-read revalidation, operator-campaign priority, bounded retry, live exception visibility, recurring canonical storage projection, and no Vehicle View dependency, Vehicle ReID behavior change, or Plate Recognizer calls; August 14, 2026 operator-controlled canonical Overview catalog with a durable exact-JPEG preview, frozen source revisions, explicit 1/5/25/250 canary batches, bounded retry and pause/resume/cancel controls, current/stale link and storage projections, archival zero-link retention, real PostgreSQL-plus-filesystem cleanup protection, and no Vehicle ReID behavior change or Plate Recognizer calls; August 14, 2026 inactive canonical Overview image-asset ownership foundation for exact JPEG deduplication and shared Entry/Street provenance; August 14, 2026 preview-first recovery of pre-fix Blue Iris 6 composite triggers through exact retained ingress receipts, unchanged camera mappings, never-started overview state, transaction-time revalidation, bounded batches, audit and per-read timeline evidence, and no historical notification replay; August 14, 2026 Blue Iris 6 composite trigger compatibility with complete sanitized receipt evidence, bounded leading ordered-crossing extraction, and fail-closed conflicting evidence; August 14, 2026 default-off logging retention health with actor-bound exact previews, typed confirmation, immutable incident evidence packages, active-incident protection, partitioned audit archiving, and bounded PostgreSQL container logs; August 13, 2026 guarded fill-only late-duplicate reconciliation with immutable established evidence, never-started Vehicle View recovery, idempotent direction-notification handoff, and sanitized timeline evidence; August 13, 2026 bidirectional expanded operational-log and ingress-receipt navigation with direct-LAN request-ID copy compatibility; August 13, 2026 append-only per-read pipeline timelines with sanitized ingestion, direction, notification-handoff, Vehicle View, and legacy Pushover outcomes; August 13, 2026 protected host-maintenance breaker acknowledgement with category-specific typed Administrator confirmation, current-breaker and fresh post-failure worker evidence, immutable acknowledgement evidence, schedules remaining off, no deletion, and a separate preview; August 13, 2026 versioned ingress receipts with sanitized trigger-alias conflict and duplicate-target read evidence; August 13, 2026 live System Logs with five-second polling, automatic pause for JSON inspection, and simplified expanded details; August 13, 2026 single-line collapsed System Logs with high-value plate context inline, secondary context tags on expansion, and exact JSON-field shortcuts; August 13, 2026 compact System Logs with default-collapsed filters, visible active-filter summaries, denser log rows, and safe Blue Iris trigger/direction context; August 13, 2026 bounded structured System Logs with correlation filters, expandable metadata, pagination, persistent request diagnostics, and normalized Blue Iris compatibility severity; August 12 guarded dual-preferred Entry route matching with a fail-closed single-read path, direct Entry Overview profile guidance, and shadow-gated Cam143 payloads for Street route fallback; August 11 unattended 250-read Entry Overview history batches plus bounded operator retry for terminal transient imports; Entry Overview primary Vehicle Views and bounded direction-independent Entry Overview history upgrades with explicit Cam143 binding, atomic legacy-view replacement, detection-focused Quick Look vehicle crops, bottom-right Quick Look captions, and Street/Entry isolation; route-scoped Vehicle Profiles and Needs Review loading, section-scoped Settings and Vehicle Setup loading, deferred Vehicle Intelligence camera-preview scans, shadow-first one-to-one Street LPR companion Vehicle View sharing, page-first Live Feed loading without a hydration refresh, production-safe Vehicle View processing-status migration compatibility, Street Overview retry-storm containment, stable export identity, integer profile revisions, claim-owned export transitions, active queue/export diagnostics, side-by-side tagged-vehicle and tagged-read distributions, persistent dashboard filters, Tag Distribution drill-downs, and bounded recovery; plus multi-camera dashboard filtering, dashboard metric and time-distribution drill-downs, camera-visible Live Feed review, mirrored results navigation, Street Overview timeline-export processing and migration compatibility, the August 8 plate-anchored daytime Vehicle View correction, Blue Iris-primary direction release, August 7 zone-crossing foundation, August 4 storage-maintenance, August 2 production-active backup, Live Feed review, storage, privacy, maintenance, notification, and Phase 2 baseline",
  filename: "ALPR-Database-Community-User-Guide.pdf",
  sections: [
    {
      id: "getting-started",
      title: "Getting started",
      summary: "Sign in safely, change a temporary password, and learn the basic page layout.",
      roles: allRoles(),
      keywords: ["login", "password", "sign in", "navigation", "first login"],
      blocks: [
        {
          type: "steps",
          title: "Sign in",
          items: [
            "Open the ALPR website and enter your username and password on the Sign In page.",
            "Use the eye button to reveal the password only when you are sure nobody else can see the screen.",
            "Select Sign In. If the password is incorrect, the password field clears automatically and receives focus so you can try again.",
            "If your account has a temporary password, follow the prompt to choose a new password. You will then return to Sign In and use the new password.",
          ],
        },
        {
          type: "bullets",
          title: "What you will see",
          items: [
            "Desktop: the icon bar on the left opens the pages your role can use. Hover over an icon to see its name.",
            "Phone or tablet: the most common pages appear in the bottom bar. Select More for the complete menu.",
            "On a large screen, place the pointer over In this guide and scroll to move through help topics without moving the article.",
            "Settings is available to every named user for personal account changes; administrative sections appear only when the account has the required permission.",
            "If a direct link opens the Forbidden page, the account is signed in but its role does not permit that operation.",
          ],
        },
        {
          type: "note",
          tone: "info",
          title: "Keep credentials private",
          text: "Do not paste passwords, session cookies, API credentials, broker passwords, or database credentials into chat, screenshots, issue reports, or exported notes.",
        },
      ],
    },
    {
      id: "roles-and-access",
      title: "Users, roles, and access",
      summary: "Choose the least-privilege role and understand which pages each role can use.",
      roles: allRoles(),
      keywords: ["administrator", "operator", "viewer", "auditor", "permission", "user"],
      blocks: [
        {
          type: "bullets",
          title: "Built-in roles",
          items: [
            "Administrator: full configuration, integrations, users, maintenance, audit, exports, and plate operations.",
            "Operator: view plate activity, review or correct reads, and manage known plates and tags. Operators cannot administer users, MQTT, notifications, exports, audit, or maintenance.",
            "Viewer: read-only access to plate pages. Viewer navigation intentionally omits mutation and administrative controls.",
            "Auditor: read-only plate pages plus database exports and System Logs/audit access. Auditors cannot change plates or configuration.",
          ],
        },
        {
          type: "example",
          title: "Example: choose a role for a new user",
          scenario: "A person needs to investigate plate activity and download records, but must not change labels, tags, users, or integrations.",
          steps: [
            "Choose Auditor because it grants plate reading, exports, and audit visibility.",
            "Do not choose Administrator merely to expose one missing page.",
            "After creating the account, sign in as that user on staging and verify both allowed and forbidden pages.",
          ],
          result: "The user can investigate and export without receiving mutation or system-management authority.",
        },
        {
          type: "note",
          tone: "warning",
          title: "Administrator safeguards",
          text: "The final active administrator cannot be disabled, demoted, or deleted. Administrative password resets and permanent deletion require the acting administrator's current password and are written to the audit history.",
        },
      ],
    },
    {
      id: "dashboard",
      title: "Dashboard",
      summary: "Use the overview cards and charts to understand recent activity.",
      roles: allRoles(),
      keywords: ["dashboard", "metrics", "charts", "camera", "time frame", "top plates"],
      blocks: [
        {
          type: "bullets",
          title: "Dashboard controls and metrics",
          items: [
            "Cameras can limit the dashboard to any combination of configured cameras. Leave the selection empty for All cameras.",
            "The dashboard remembers the selected cameras and time frame in this browser across refreshes, sign-in cycles, and application restarts. Cameras that are later removed from configuration are discarded automatically.",
            "The selected camera set applies to the summary cards, Time Distribution, Top Plates and their previews and links, Camera Activity, and Tag Distribution.",
            "Time frame changes the period used by total reads, unique vehicles, new vehicles, time distribution, camera counts, and top plates.",
            "Select Total Reads, Unique Vehicles, or New Vehicles to open Recognition Feed with the same exact time window and every selected camera. Unique and new vehicle results show one most-recent read for each effective plate identity; reviewed corrections use the corrected plate while the original OCR observation remains preserved as evidence.",
            "Select a time-distribution bar to open Recognition Feed with the same exact time window, local hour, and every selected camera as that dashboard column. This applies to Last 24 Hours, Last 3 Days, Last 7 Days, Last 30 Days, and All Time.",
            "The Tag Distribution card presents two side-by-side charts. Tagged Vehicles counts each corrected plate identity once per tag and opens one latest Recognition Feed result per vehicle. Tagged Plate Reads counts every matching capture and opens all matching reads. Each chart's slices, legend rows, and center total preserve the selected time window and every selected camera; on narrow screens the two views stack for readability.",
            "Hover over a top plate to preview its four most-recent captures. When any of those reads has a ready Vehicle View with a valid detected-vehicle crop, the best direct Entry or Street overview replaces only the bottom-right preview and focuses the thumbnail on that vehicle; otherwise all four plate captures remain unchanged. Timestamp and Overview captions appear as compact badges in each image's bottom-right corner. The original full-resolution overview remains unchanged. Select the reads count to open all matching appearances.",
            "The header links open the community documentation, fork source, product roadmap, and this Help Center.",
          ],
        },
        {
          type: "note",
          tone: "info",
          title: "Empty dashboard",
          text: "Waiting for License Plate Data means the application is ready but no accepted reads match the selected camera and time frame. It is not, by itself, a database error.",
        },
      ],
    },
    {
      id: "recognition-feed",
      title: "Recognition Feed",
      summary: "Browse individual reads, filter activity, inspect images, and control live updates.",
      roles: allRoles(),
      keywords: ["live feed", "recognition feed", "filter", "sorting", "live updates", "camera", "confidence"],
      blocks: [
        {
          type: "steps",
          title: "Find a group of reads",
          items: [
            "Open Live Feed and expand Search options.",
            "Enter a complete or partial plate, then choose a Plate matching mode when approximate OCR matching is useful.",
            "Optionally narrow the results by tag, camera, date, or hour.",
            "Use either results row above or below the table to review the shown range, move to Previous or Next, or jump to the top or bottom of the page.",
            "Select a sortable column heading to switch between ascending and descending order.",
            "Saved page-size and plate-matching preferences are applied on the first response, so opening Live Feed does not require a second navigation. Filtering and paging select the requested read identities before loading their presentation details, and timestamps reserve their final two-line layout immediately.",
            "Keep Live updates enabled for monitoring. Disable it while reviewing a stable result set so new reads do not move the rows.",
          ],
        },
        {
          type: "bullets",
          title: "Row and image actions",
          items: [
            "Select a thumbnail to inspect the larger capture and read details. When crop coordinates are available, the viewer opens focused on the plate. Scroll the mouse wheel over the image or use the slider to zoom continuously; select Reset to return to the full image.",
            "The popup summary identifies the observed and effective plate, review status, occurrences, camera, known-plate name, tags, and assigned vehicle.",
            "Select Previous Read or Next read to move through the filtered Live Feed results in either direction. Navigation continues across result pages instead of wrapping. Left Arrow and Right Arrow provide the same review navigation from the keyboard.",
            "The popup remembers the last Plate capture or Vehicle view selection in this browser, including after signing out and back in. Reads without a vehicle image temporarily show the plate capture without changing that saved preference.",
            "Select Confirm and Next to confirm an unreviewed read and, only after confirmation succeeds, advance to the next unconfirmed read. Already confirmed reads are skipped, including across result pages; if no later unconfirmed read can be found, the viewer stops instead of wrapping. Plate corrections preserve the cursor or selection when editing in the middle of the value.",
            "The two popup action rows use aligned fixed-width columns, so review status changes and unavailable optional actions do not move Next read or neighboring controls.",
            "Use Add tag or Remove tag to change classification when your role permits tag management.",
            "Use Confirm detected plate, Correct this read, Reject, Reopen, or Reverse review only after inspecting the original image.",
            "Delete is destructive and appears only for accounts with plate deletion permission.",
          ],
        },
        {
          type: "note",
          tone: "warning",
          title: "Matching is a candidate finder",
          text: "Approximate plate matches are not proof that two sightings are the same vehicle. Confirm the image, camera, time, and original observed OCR before taking action.",
        },
      ],
    },
    {
      id: "plate-matching",
      title: "Plate matching profiles",
      summary: "Choose Off, Strict, Balanced, or Broad without hiding how approximate matching behaves.",
      roles: allRoles(),
      keywords: ["fuzzy", "strict", "balanced", "broad", "ocr", "matching", "search"],
      blocks: [
        {
          type: "bullets",
          title: "Profile guide",
          items: [
            "Off: normal exact or partial text search. MQTT identity rules remain exact.",
            "Strict: favors the lowest false-positive rate and only accepts narrowly defined OCR-equivalent differences.",
            "Balanced: handles common OCR confusion and at most one ordinary difference within configured limits. This is the best starting point for a suspected misread.",
            "Broad: allows a wider candidate set for poor captures. Review the images carefully because false positives increase.",
            "Settings > Plate Matching lets an administrator configure minimum length, OCR-equivalent groups, insertion/deletion behavior, adjacent transpositions, and limits, then test two values interactively.",
          ],
        },
        {
          type: "example",
          title: "Example: search for a likely OCR misread",
          scenario: "The image looks like ABC128, but a prior camera read may have stored ABC123.",
          steps: [
            "Search for ABC128 with Off first to find exact and ordinary partial matches.",
            "If the expected sighting is missing, choose Balanced and search again.",
            "Inspect every candidate's image and timestamp. Use Broad only if Balanced is still too narrow.",
            "If ABC123 is a repeated, confirmed misread, an administrator can create an explicit recurring alias after correction.",
          ],
          result: "The search broadens gradually while the final identity decision remains a human review.",
        },
      ],
    },
    {
      id: "reviews-and-aliases",
      title: "Reviewing, correcting, and recurring aliases",
      summary: "Correct effective identity without destroying what the camera originally observed.",
      roles: ["administrator", "operator"],
      keywords: ["confirm", "correct", "reject", "reverse", "batch", "alias", "observed plate", "history"],
      blocks: [
        {
          type: "paragraph",
          text: "Every read keeps an immutable observed plate from the camera. Reviews change the effective plate used by searches, known-plate data, tags, rules, notifications, and MQTT while preserving the original evidence and append-only history.",
        },
        {
          type: "example",
          title: "Example: correct one read without losing evidence",
          scenario: "The camera reported ABC123, but the image clearly shows ABC128.",
          steps: [
            "Open the capture from Recognition Feed and compare the image with the observed plate.",
            "Select Correct this read and enter ABC128.",
            "Add a concise reason such as Clear final digit in full image and optional notes.",
            "Leave batch correction off unless the preview shows that every selected match is the same mistake.",
            "Apply the correction and open review history to confirm that ABC123 remains the observed plate while ABC128 is effective.",
          ],
          result: "Existing evidence remains immutable, and downstream known-plate, tag, rule, notification, and MQTT behavior uses ABC128.",
        },
        {
          type: "example",
          title: "Example: create a camera-scoped recurring alias",
          scenario: "Driveway West repeatedly reads ABC128 as ABC123, while another camera may legitimately see ABC123.",
          steps: [
            "Correct a verified Driveway West read from ABC123 to ABC128.",
            "Choose Remember as recurring alias and scope the alias to Driveway West.",
            "Preview the source, target, and camera scope before saving.",
            "Open Settings > Review & Corrections to confirm the alias is enabled.",
            "If the rule later proves unsafe, disable it. Aliases are retained for audit and cannot be deleted.",
          ],
          result: "Future exact ABC123 observations from only Driveway West resolve to ABC128; the original observed value and alias application remain auditable.",
        },
        {
          type: "note",
          tone: "warning",
          title: "Batch correction requires preview",
          text: "Batch correction is administrator-only. Review the server-generated scope and count, and never use a broad search result as automatic identity proof. Reverse the latest review when an approved correction must be undone.",
        },
        {
          type: "note",
          tone: "info",
          title: "Repairing an incorrect recurring alias",
          text: "If the read already has the correct effective plate, enable Remember as recurring misread and use Save recurring alias; no batch correction is needed. When an enabled alias conflicts, Replace alias disables the prior mapping and creates the reviewed replacement while retaining both records for audit. Review reversal separately confirms whether its associated active alias should also be disabled.",
        },
      ],
    },
    {
      id: "plate-database",
      title: "Plate Database",
      summary: "Search summarized plate identities, sort every supported field, and carry filters into exports.",
      roles: allRoles(),
      keywords: ["database", "search options", "name", "notes", "tag", "camera", "date", "hour", "sorting"],
      blocks: [
        {
          type: "steps",
          title: "Build a precise database view",
          items: [
            "Open Database and expand Search options.",
            "Search by plate, known name, or notes and choose the matching profile.",
            "Combine the search with tag, camera, date, and hour filters as needed.",
            "Choose a page size and select a column heading to sort by plate, occurrences, name, notes, first seen, last seen, or tags.",
            "Use either results row above or below the table to review the shown range, move to Previous or Next, or jump to the top or bottom of the page.",
            "Use Clear controls to remove the complete filter set before starting another investigation.",
          ],
        },
        {
          type: "bullets",
          title: "Important behavior",
          items: [
            "Plate Database summarizes effective plate identities; Recognition Feed shows individual read events.",
            "Blank optional values sort last in both directions so missing names or notes do not hide populated rows.",
            "View insights opens aggregate details for the selected plate.",
            "Export these results preserves the current filters, matching mode, and sorting on the Downloads page when your role permits exports.",
          ],
        },
      ],
    },
    {
      id: "known-plates-tags-watchlist",
      title: "Known Plates, tags, and Monitored Plates",
      summary: "Attach human context to plate identities and manage focused monitoring safely.",
      roles: ["administrator", "operator", "viewer", "auditor"],
      keywords: ["known plates", "tags", "watchlist", "flagged", "name", "notes"],
      blocks: [
        {
          type: "bullets",
          title: "Known Plates",
          items: [
            "Known Plates can store a name and notes for a plate identity and display its tags.",
            "Select a license plate value to open Live Feed with exact matching and review its individual reads.",
            "Select any supported column heading to sort. Sorting is stable, numeric-aware, case-insensitive, and keeps blank optional values last.",
            "Administrators and Operators can edit known-plate details and tags. Viewers and Auditors can read them without mutation controls.",
            "Plate identifiers use a slashed zero wherever the active font supports the OpenType slashed-zero glyph, helping distinguish 0 from O.",
          ],
        },
        {
          type: "bullets",
          title: "Tags and Monitored Plates",
          items: [
            "Use tags for reusable classifications such as family, delivery, service, or vehicle color. A tag can appear in search and MQTT matching.",
            "Monitored Plates replaces the separate Watchlist page and is available as a view inside Known Plates. Existing flagged-plate data remains compatible with rule evaluation.",
            "For each monitored plate, record a reason, choose low, normal, high, or critical priority, and review monitoring-since, last-seen, read-count, tag, and exact-history context.",
            "A unified rule with the monitored-plate condition decides which cameras and delivery channels act on a monitored read. Priority is operator context and does not enable delivery by itself.",
            "Before removing a tag, consider how it affects saved searches, MQTT rules, and operational habits.",
          ],
        },
      ],
    },
    {
      id: "push-notifications",
      title: "Notification rules and delivery channels",
      summary: "Configure each delivery integration separately, then build, preview, activate, and troubleshoot notification rules from a focused workspace.",
      roles: ["administrator"],
      keywords: ["notification", "pushover", "email", "smtp", "webhook", "signature", "priority", "test", "alert"],
      blocks: [
        {
          type: "steps",
          title: "Create a unified notification rule",
          items: [
            "Open the needed service directly under Settings > Integrations. MQTT, Pushover, Email, and Webhook each have a dedicated tabbed setup page; there is no separate Integrations overview page. Never include credentials or secrets in screenshots or support messages.",
            "For email, open Settings > Integrations > Email. Use the SMTP Connection, Sender Identity, and Test tabs to configure and verify delivery. Keep certificate verification enabled unless you fully control and trust the relay.",
            "For webhooks, open Settings > Integrations > Webhook. Use Signing & Delivery, Network Safety, and Test. Prefer HTTPS; HTTP and private-network targets require explicit permission, while loopback, link-local, special-use targets, URL credentials, redirects, and fragments remain blocked.",
            "For Pushover, open Settings > Integrations > Pushover. Connection holds enablement and credentials, Defaults controls presentation, Usage shows the monthly allowance and remaining messages, and Test sends a direct alert. Select Refresh usage after changing the application token or sending a test.",
            "Open Notification Rules from the left sidebar. On the Rules tab, select Create rule and enter a name, optional description, cooldown in seconds, and the explicit rule time zone. Every new draft resolves the browser-local time zone when Create rule is selected; quiet hours and new Schedule conditions inherit that rule time zone. Unified rules preserved by a completed legacy finalization or retirement appear in this normal Rules list.",
            "Choose Accepted plate read for an arrival rule. Choose Scheduled camera activity to detect no or fewer than a configured number of camera reads within a period; select the camera, use a camera-scoped Read count condition, and choose how often the server checks it.",
            "Choose whether each group requires All (AND), Any (OR), or Not. Add nested groups as needed, up to six levels deep. Conditions can match any accepted read, a plate, a known plate, a tag, a Monitored Plate, one or more cameras, confidence, read counts, or a local weekday/time schedule.",
            "Tag and Known plate are independent conditions. A Tag condition matches the effective plate's assigned tags even when that plate is not in Known Plates; add a separate Known plate condition only when both facts are required.",
            "Plate matching supports the shared fuzzy profiles plus explicit exact, contains, wildcard (* and ?), OCR-confusion-only, and bounded edit-distance strategies.",
            "For Read count, select the same plate, same camera, or all reads; choose the comparison and count; then select Lifetime or enter a period in minutes, hours, or days. Counts are evaluated at each read's persisted event time, including that read.",
            "Add one or more actions. MQTT uses an existing broker and a per-camera or fixed topic. Pushover can specify priority and a message. Email specifies up to 10 recipients, an optional subject/message, and whether to attach the capture. Webhook specifies a target URL and optional message. Credentials remain protected in Settings rather than being copied into rules.",
            "Optionally enable Quiet hours, enter the local start/end times, choose weekdays, and verify the time zone. A matched event during quiet hours is recorded as suppressed and does not queue delivery.",
            "Select Save disabled draft. Saving or editing cannot enable the rule and makes no delivery attempt.",
            "Select Preview to evaluate the saved version against up to 25 recent real reads. Review matched and non-matched rows and expand any row to inspect its complete condition trace; the preview always reports zero delivery attempts.",
            "When the result is correct and every selected channel is ready, select Activate and confirm the separate prompt. Activation enables the rule, channel, and actions atomically and records an audit event.",
            "Select Deactivate to pause all actions atomically. An active rule must be deactivated before it can be edited, and every saved edit increments its version.",
            "To remove a rule, deactivate it first and then select Delete. Confirm the exact rule name and version in the popup. The rule immediately disappears from Notification Rules and can never evaluate or deliver again; historical activity and audit references remain available.",
            "Open the Activity & delivery tab to review each recent decision, its event-time trace, suppression reason, channel delivery state, retry attempts, and dead-letter error. MQTT, Pushover, email, and webhook delivery failures are handled asynchronously without holding open plate ingestion.",
          ],
        },
        {
          type: "note",
          tone: "warning",
          title: "Rules use guarded activation",
          text: "Rules use disabled drafts, no-delivery preview, separate audited activation, atomic deactivation, and protected credential references. Unified MQTT, Pushover, email, and webhook actions use durable, deduplicated delivery ledgers with bounded retries and dead-letter state. Webhook receivers should verify the HMAC-SHA256 X-ALPR-Signature against the raw JSON body and deduplicate with Idempotency-Key.",
        },
      ],
    },
    {
      id: "mqtt",
      title: "MQTT integration",
      summary: "Connect brokers, map cameras and topics, and test MQTT delivery while managing all automation from Notification Rules.",
      roles: ["administrator"],
      keywords: ["mqtt", "broker", "rule", "topic", "camera", "outbox", "test"],
      blocks: [
        {
          type: "steps",
          title: "Safely configure MQTT",
          items: [
            "Open Settings > Integrations > MQTT and add the broker connection first. The former /mqtt address redirects here. Use a dedicated, least-privilege broker account when possible.",
            "Test the broker connection before creating a rule in Notification Rules. A successful broker test proves connectivity, not that a rule is correct.",
            "Review detected camera mappings and the per-camera topic before enabling automation.",
            "Open Notification Rules and create a disabled rule. Add an MQTT action, select its broker and destination, and configure the trigger and conditions there.",
            "Review the rule summary, preview recent matches, then activate it during a supervised test window and check MQTT activity for delivery or retry status.",
            "Expand Payload and attempts in Delivery Activity to confirm the plate, matched rule, runtime, attempt count, and final outcome without exposing broker credentials.",
          ],
        },
        {
          type: "example",
          title: "Example: publish a delivery tag",
          scenario: "Home automation should receive accepted reads tagged Delivery from the driveway camera.",
          steps: [
            "Confirm the Delivery tag exists and is assigned consistently.",
            "Create a unified rule on Notifications with a Tag condition whose value is Delivery and add an MQTT action.",
            "Add a driveway Camera condition and select the intended broker in the MQTT action.",
            "Choose the exact fixed topic or verify the per-camera destination preview.",
            "Leave plate matching Off because tag matching does not need approximate plate identity.",
            "Save disabled, review it, then enable and observe one controlled test read.",
          ],
          result: "Only accepted driveway reads carrying the Delivery tag enter the durable MQTT delivery flow.",
        },
        {
          type: "note",
          tone: "warning",
          title: "Avoid automation loops",
          text: "Do not publish to a topic that another integration converts back into the same ALPR input. Keep test topics separate from production automation and verify retained-message behavior on the broker.",
        },
      ],
    },
    {
      id: "exports",
      title: "Downloads and exports",
      summary: "Download bounded CSV or JSON results using the same filters as Plate Database.",
      roles: ["administrator", "auditor"],
      keywords: ["download", "export", "csv", "json", "filter", "spreadsheet"],
      blocks: [
        {
          type: "example",
          title: "Example: export the exact filtered investigation",
          scenario: "You need all Balanced matches for ABC128 from Driveway West during the previous week, sorted newest first.",
          steps: [
            "Build the view in Plate Database: search ABC128, choose Balanced, select Driveway West, set the date range, and sort Last seen descending.",
            "Select Export these results. Downloads opens with the same search, matching mode, camera, dates, and sorting.",
            "Confirm every filter before downloading.",
            "Choose CSV for spreadsheet analysis or JSON for structured processing.",
          ],
          result: "The export contains up to 50,000 matching database records and reports when the result was truncated.",
        },
        {
          type: "bullets",
          title: "Export safety",
          items: [
            "CSV fields are escaped and spreadsheet-formula prefixes in user-controlled text are neutralized.",
            "Exports contain database text and timestamps, not a ZIP of capture images.",
            "Treat exported plate activity as sensitive data. Store it only where authorized and remove copies when they are no longer needed.",
          ],
        },
      ],
    },
    {
      id: "blue-iris-recordings",
      title: "Blue Iris continuous recordings",
      summary: "Connect to Blue Iris read-only and verify that plate-read times can be correlated with alerts in continuous BVR recordings.",
      roles: ["administrator"],
      keywords: ["blue iris", "bvr", "continuous recording", "alert", "clip", "drivepool"],
      blocks: [
        {
          type: "steps",
          title: "Configure safe alert correlation",
          items: [
            "Create a dedicated Blue Iris account that can view the LPR cameras, alerts, and clips but cannot administer Blue Iris or delete recordings.",
            "Open Settings > Blue Iris. Enter the Blue Iris HTTP or HTTPS server address and optional port, username, password, and request timeout, then select Save Changes.",
            "Select Test connection. The result lists the camera identifiers returned by Blue Iris without exposing the saved password.",
            "Choose a camera and enter the local timestamp of a known plate read, then select Find matching alert. Start with a 90-second tolerance and narrow it after camera identifiers and clocks are verified.",
            "Open Settings > Vehicle Setup > Vehicle Views. Under Daytime overview association, add one primary mapping for each validated plate-camera direction. Use Street Overview for Street LPR mappings and Entry Overview for Entry LPR mappings. Enter Overview time minus plate-read time as the expected delta and measure each installed pair rather than copying another camera's timing.",
            "For Entry mappings, choose Entry use, enter Entry Overview as the source display name, and bind it to the Blue Iris short name Cam143. Configure Entry LPR 1 and Entry LPR 2 independently for Entering and Exiting after measuring their signed deltas and tolerances.",
            "Do not add a Street Overview or Entry Overview Blue Iris motion or web-request action. After the existing plate-camera action is accepted, ALPR asks Blue Iris to export one temporary segment from the configured continuous overview recording, using the calculated UTC start.",
            "For each mapped color daytime read, ALPR adds the profile's signed timing delta to the plate-read timestamp. It exports an eight-second padded segment, then uses FFmpeg locally to normalize timestamps and extract exactly 61 analysis frames at 100-millisecond intervals across the intended six-second window. The window begins one configured tolerance before the anchor and ends at 6000 milliseconds minus that tolerance. Primary tolerance is limited to 3000 milliseconds so the calculated anchor remains inside the window.",
            "Vehicle selection is constrained to the track nearest the calculated anchor. If nearby competing tracks cannot be distinguished, ALPR refuses the assignment instead of choosing the best-looking unrelated vehicle.",
            "ALPR waits for the complete profile-derived window, the export post-padding, and a short Blue Iris recording-finalization grace period. Blue Iris 6 may reject status queries for an accepted reserved @record, so ALPR checks the exact reserved download URI no more often than every five seconds. Only an available owned URI permits the full download, which must then pass FFprobe duration, alignment, and resolution validation; absence from the global queue is never treated as completion. Each semantic read, source window, and integer profile revision has one stable export identity. A retry or worker restart resumes that ledger and URI and cannot send a second automatic export request. Temporary export, download, or media failures receive at most one delayed retry; the second failed attempt is classified instead of remaining Processing.",
            "ALPR explicitly requests a direct-copy main-stream export with re-encoding disabled. It verifies the downloaded file's UTC coverage, duration, and minimum configured resolution with FFprobe, and fails closed if Blue Iris returns an undersized or unverified file. Analysis uses bounded 1280-pixel frames, but the final Vehicle View is extracted from the original downloaded export at the exact same 10-fps slot without changing the selected time or vehicle.",
            "After a verified download, ALPR leaves the API-generated export in the Blue Iris Clipboard folder. Blue Iris owns its age and size retention, so the restricted ALPR account never needs Administrator deletion permission. The local clip and 61 temporary frames are removed after the read finishes, and abandoned local workspaces are swept safely.",
            "New daytime Street and Entry plate reads use their configured read-owned overview retrieval and do not sample the plate camera for a normal live Vehicle View. Entry results are stored with separate Entry Overview provenance and cannot enter Street companion sharing. A nighttime plate read immediately displays Unavailable nighttime, is not queued, and makes no Blue Iris connection, export, or frame requests.",
            "For older Entry LPR reads, use the dedicated Entry Overview history card rather than the generic camera-history controls. Save one measured direction-independent Cam143 timing anchor for Entry LPR 1 and one for Entry LPR 2, enter an exact local start and exclusive end, and select Preview. Preview freezes the eligible set and changes no reads.",
            "Confirm history in batches of 1, 5, 25, or 250. Begin with one read, then widen only after its Cam143 provenance, timing, full-resolution image, crop, and single stable export are verified. The 250-read option still processes one clip at a time and is intended for an already-validated unattended campaign. Queue the next bounded batch until Previewable remaining reaches zero. History always yields to live work and can be paused, resumed, or cancelled without discarding completed images.",
            "When a historical Entry import exhausts both automatic attempts because of a transient export, connection, download, media-tool, deadline, or processing failure, Vehicle Views lists it under Failed imports eligible for retry. Select Retry failed import to grant that exact job one bounded manual retry cycle. The original job and stable Blue Iris export identity are reused, a current image remains visible until a validated replacement commits, and successful, nighttime, no-vehicle, and multi-vehicle outcomes cannot be retried through this control.",
            "Historical Entry processing uses the retained plate image only to prove daytime color before any Blue Iris call. It does not invent a direction. Monochrome evidence becomes Unavailable nighttime without contacting Blue Iris; missing or unreadable evidence remains daylight-unverified. Entry Overview video is checked again after export.",
            "Legacy Entry LPR Vehicle Views are upgraded only after a new Cam143 image has downloaded, validated, selected, and atomically committed. The old image remains available throughout processing and on every failure or cancellation; its file is removed only after the successful database swap. Existing Entry Overview primary or historical images are preserved.",
            "Open Settings > Vehicle Setup > Vehicle Views to queue missing historical vehicle views for one camera or all cameras, optionally expand the date-range controls, and pause or resume only historical work. Queueing always leaves history paused until Resume history is selected. Cancel pending history safely removes pending or retryable historical jobs for the selected camera and optional date range while preserving completed images, live work, and manual retries.",
            "Use the Vehicle Views status panel to verify the active overview queue, processing count, ready and failed outcomes, Blue Iris export starts, and last worker error. The export ledger records the stable job fingerprint, current claim, requested window, URI state, dimensions, and terminal result so duplicate or stalled work is diagnosable without relying on the retired candidate queue.",
            "Street LPR companion sharing is a separate fallback after normal primary processing. Shadow mode records future one-to-one proposals without changing reads or files. After those proposals are verified, Active may copy one validated overview_primary image into a separate file for a companion read that ended with Vehicle not visible or final Recording unavailable. Exact corrected plate identity, Blue Iris direction, different Street LPR cameras, the same Overview source, profile revisions, camera order, derived-anchor agreement, and a unique source and target are all required.",
            "Companion sharing never interrupts an in-progress primary job, overwrites a successful image, chains from another shared or fallback image, or fills a multi-vehicle, nighttime, daylight, direction, profile, or configuration outcome. The source read remains independently stored and the target records its source read and full decision provenance.",
            "Entry LPR route fallback remains a separate read-to-read layer after primary Street Overview retrieval and companion Street sharing. Add only explicit routes that begin with an existing Street plate read and specify the Street camera and direction, two configured Entry LPR cameras, Entry direction, signed expected delta, tolerance, and inter-camera event window. Two matching Entry reads are preferred, but one may qualify when it alone has authoritative matching Blue Iris direction, acceptable plate identity, a ready daytime Cam143 Vehicle View, and no competing plausible event. Cam143 is image evidence only and never establishes the association.",
            "Cam143 fallback payloads have a separate Off, Shadow, or Active guard. Keep both route matching and Cam143 payloads in Shadow while reviewing proposals. A writable proposal must use a ready daytime entry_overview_primary image owned by the direction-authoritative Entry evidence read, with Entry Overview/Cam143 provenance and immutable image geometry. Active copies that already-validated image into a separate target-read file; it never copies the raw Entry plate image, overwrites a ready target, or uses an unrelated Entry Overview frame.",
            "Entry fallback accepts exact corrected plate identity first. A single confusion-normalized edit is permitted for plates of at least five characters only when route timing is bounded, the selected Entry read has authoritative matching direction and a valid Cam143 payload, and the best event has a clear margin. Dual-camera evidence remains stronger and is preferred. Conflicting direction, short fuzzy plates, nighttime evidence, and competing events fail closed. It never fills a successful primary outcome or synthesizes a missing Street read for a driveway exit that turns westbound without an ingested Street plate.",
            "New incoming reads preserve the Blue Iris clip, alert path, and offset metadata supplied by the existing Blue Iris action. Historical reads can be matched by camera and timestamp through Blue Iris alertlist metadata.",
            "For LPR direction setup, open Settings > Vehicle Setup > Cameras, select the camera, and map two exact reverse Blue Iris trigger values such as MOTION_A>B and MOTION_B>A to the existing semantic direction labels. Enable Blue Iris zone-crossing direction only after both mappings have been verified with live traffic.",
            "In Blue Iris, preserve the existing plate alert and use explicit ordered zone rules such as A>B,B>A rather than the bidirectional shorthand A-B. Add \"trigger_type\":\"&TYPE\" to the existing JSON web-request payload. The plate, camera, alert pointer, timestamp, and ordered crossing then arrive in one authenticated request.",
            "Review the selected camera's received, mapped, unknown, and unmapped totals under Vehicle Setup. For new daytime reads received after this release, a mapped Blue Iris crossing supplies the displayed direction and direction notification event immediately. Missing, disabled, shorthand, and unmapped crossings fall back to the existing single-frame Vehicle ReID result. Monochrome nighttime captures bypass both sources, display Unavailable nighttime, and do not send direction notifications. Existing historical directions and legacy shadow observations are not rewritten or backfilled.",
            "Open the read in Recognition Feed and use Plate capture or Vehicle view to switch between the immutable ALPR image and the derived Blue Iris overview image. While direct overview retrieval is queued, the overlay reports the pending Vehicle View. A nighttime read says Unavailable nighttime. No-vehicle, ambiguity, and legacy plate-camera outcomes use separate plain-language messages.",
            "Retry vehicle view appears only for an older manual or historical operation whose failure can benefit from another attempt. It is hidden for nighttime reads and other terminal overview outcomes, where retrying the plate-camera window would not help.",
          ],
        },
        {
          type: "note",
          tone: "info",
          title: "Recordings stay in Blue Iris",
          text: "ALPR never mounts DrivePool volumes, parses BVR files, changes retention, or deletes continuous recordings. Primary overview selection uses Blue Iris's timeline export API to create one short, read-owned temporary MP4 from the configured Street Overview or Entry Overview continuous recording. It waits until the exact reserved download URI is available, downloads and validates that export, analyzes local 100-millisecond frames, stores one read-owned JPEG, and deletes its local workspace. Blue Iris retains its Clipboard copy according to the Clipboard folder's configured age and size limits; ALPR never sends a remote delete request. Older overview-candidate records remain inert for compatibility. The former dense clip vehicle-direction experiment remains removed: direction uses only the ordered trigger metadata Blue Iris already calculated, while local 100-millisecond analysis is limited to selecting a daytime overview still image.",
        },
      ],
    },
    {
      id: "settings-audit-privacy",
      title: "Settings, users, audit, and privacy",
      summary: "Understand personal settings, administrative controls, audit history, and local-only privacy behavior.",
      roles: allRoles(),
      keywords: ["settings", "user management", "audit", "logs", "privacy", "retention", "password"],
      blocks: [
        {
          type: "bullets",
          title: "Settings and administration",
          items: [
            "Every named user can change their own password from personal settings.",
            "Administrators can manage users, system settings, integrations, plate matching profiles, and recurring aliases when the related permission is present.",
            "System Logs is available to Administrators and Auditors. It shows the bounded active application log newest first. Filters are collapsed by default so more entries remain visible; expand Filters for log level, component, camera, request ID, read ID, time range, full-field search, and rows-per-page controls. The compact toolbar summarizes active filters and keeps Refresh available. Live updating is enabled by default and refreshes the newest page every five seconds; it pauses on older pages, while the browser tab is hidden, whenever any log entry is expanded for JSON inspection, or while a durable read timeline is open, then resumes automatically. The Live control can also pause or resume updates manually. Collapsed entries remain one line; when space permits, Blue Iris rows keep only the camera, trigger type received from &TYPE, evaluated direction, and first read ID inline. Select a row to reveal secondary component, request, direction-error, and additional-read tags with sanitized JSON immediately below. Each tag highlights its exact JSON field. The copy action works on both HTTPS and direct-LAN HTTP installations, and plate-ingress rows provide a receipt action that filters Ingress Receipts by the same request ID and opens its first match. When Logs is opened for a specific read, the compact Durable read timeline separates persistent read, direction, notification-handoff, Vehicle View, and legacy Pushover outcomes from rotating operational logs. The timeline is collapsed by default, contains only allowlisted non-sensitive outcome evidence, and begins with reads accepted after this release; older reads continue to show their available operational logs and ingress receipts.",
            "Ingress Receipts is available beside Operational Logs to Administrators and Auditors. It retains bounded metadata rather than request values. Expand a receipt to see its schema version, recognized field names, trigger aliases, whether aliases conflicted, large-field size summaries, and body fingerprint. Request and read log actions filter Operational Logs to the correlated evidence and open its first JSON row; the request-ID copy action also supports direct-LAN HTTP. Produced reads and duplicate-target read IDs link to the exact Recognition Feed record and their operational logs. Alias diagnostics never expose alternate trigger values, and receipts never store API keys, plate values, request bodies, images, AI dumps, or Blue Iris paths.",
            "Retention & incidents is available beside Operational Logs and Ingress Receipts. Administrators and Auditors can review operational-file, receipt, read-timeline, and hot/archive audit growth and export existing incident packages. An Administrator can protect one request ID, one read ID, or a time window of at most seven days; Protect and snapshot immediately captures a bounded immutable JSON evidence package and excludes matching live receipt and audit rows from retention until the displayed protection date. The package itself remains append-only after protection expires. Cleanup never runs on a schedule: Create retention preview changes nothing, is valid for 15 minutes and only for the same Administrator, and lists the exact expired receipt and old audit rows. Type ARCHIVE LOG EVIDENCE to execute that exact preview. Old audit rows are copied and verified in the immutable partitioned archive before leaving the hot table; expired receipts are then removed. If the candidate set changes, the preview is invalidated and no evidence is changed. Read-timeline retention continues to follow the parent read lifecycle, while operational and PostgreSQL container logs use bounded file rotation.",
            "Exact late duplicates remain reported as duplicates, but ingestion now locks the existing target and may fill only missing, nonconflicting source-image, Blue Iris alert, recognition, or direction evidence. Established values are never replaced. General MQTT, unified notifications, legacy Pushover, completed work, active work, and previously attempted work are not replayed.",
            "When safe evidence was actually attached, the target read's Durable read timeline adds a duplicate-reconciled event showing only which evidence groups changed and whether never-started Vehicle View work or a new idempotent direction notification was queued. The ingress receipt continues to link to the duplicate target without storing raw values.",
            "Data & Privacy is local status and configuration. Upstream telemetry, AI-training uploads, and remote update polling have been removed from this fork.",
          ],
        },
        {
          type: "note",
          tone: "info",
          title: "Audit history is intentionally durable",
          text: "Security, user-management, and review events are retained to explain who changed what and when. Deleting a user scrubs the login identity while retaining an audit tombstone rather than erasing history.",
        },
      ],
    },
    {
      id: "maintenance-updates",
      title: "Maintenance, backups, and updates",
      summary: "Use the established deployment process without exposing unrestricted host control inside the website.",
      roles: ["administrator"],
      keywords: ["maintenance", "backup", "update", "migration", "restore", "health", "rollback"],
      blocks: [
        {
          type: "bullets",
          title: "Read storage health safely",
          items: [
            "Administrators can open Settings > Data & Privacy and use the Storage Health, Monitoring, Cleanup, and Privacy tabs. Each tab has a clean address that can be bookmarked or restored with browser navigation.",
            "Storage Health contains capacity, category, database, capture, visual-index, projection, and read-only PostgreSQL statistics. Monitoring contains thresholds, scheduler liveness, reconciliation, and alert destinations. Cleanup contains derived-orphan and host-retention controls. Privacy contains the local-only reporting and explicit-integration policy.",
            "Mounted filesystem capacity and PostgreSQL size are direct measurements. Completed reconciliation provides exact source-image, thumbnail, and derived-file counts and bytes. Docker and backup totals appear only from a current read-only host snapshot and otherwise remain clearly unavailable.",
            "Reads/day uses the last seven days. Estimated bytes/read samples at most 120 recent source, thumbnail, and derived files; it does not recursively scan the storage tree.",
            "Capacity dates are planning estimates, not promises. Logs, backups, database overhead, and other files sharing the mount can move the dates. Warning and critical thresholds control health state and alerts.",
            "Index-confirmed missing sources counts current failed visual assets with SOURCE_IMAGE_MISSING. Reads without an image path are reported separately.",
            "Retention and record-limit planning runs in a scheduled single-flight worker instead of plate ingestion. Its results remain dry-run previews based on database references and never delete rows or files.",
            "Read-only storage reconciliation walks only images, thumbnails, and derived storage roots in bounded resumable batches. It records exact orphaned-file and missing-reference paths, totals, sizes, progress, and a review sample without deleting anything.",
            "Files created after a reconciliation starts are deferred to the next run. Symlinks, invalid paths, and access errors are skipped and reported rather than classified as cleanup candidates.",
            "Run preview now refreshes maintenance evidence without deletion. Manual cleanup is a separate typed-confirmation action limited to generated derived files that remain unreferenced after fresh database, real-path, symlink, size, and modification-time checks.",
            "Automatic cleanup defaults to disabled and uses a separate Administrator-only, typed, actor-recorded approval. The sole supported category is reconciliation-confirmed generated derived orphans. Each run requires the latest reconciliation to be completed, fresh, and error-free; candidate mtimes must predate both the scan start and the seven-day grace cutoff.",
            "An automatic run handles at most 100 files or 1 GiB and admits new candidates for at most five minutes, without catch-up loops. Per-candidate database lock and statement waits use the remaining scheduling budget; a filesystem operation already in progress is allowed to finish safely. It rechecks the current approval revision between files and uses the same five-column reference, advisory/writer lock, table lock, real-path, symlink, hard-link, size, mtime, device, and inode safeguards as manual cleanup. A failure suspends automation, makes reconciliation due, and requires a newer successful reconciliation plus typed Administrator acknowledgement.",
            "Host artifact retention has three independent boundaries: Docker build cache, unused ALPR and maintenance-worker images, and verified rollout backups. Preview candidates and opaque tokens come only from a separately installed fixed host worker; the browser never supplies a path, image ID, backup ID, or command.",
            "While a host-maintenance preview or cleanup is pending or processing, the Cleanup page follows its status automatically, updates both the request card and summary metrics from the same request, and preserves the active request across a server refresh. Pending previews say Calculating instead of presenting zero as a result, and the preview button remains disabled until that category finishes; the server also serializes category requests to prevent duplicate queue entries. The normal view has no manual status button; Retry status update appears only if automatic updates pause after repeated interruptions.",
            "Administrators can request one manual PostgreSQL custom-format database backup from the Cleanup page only when the fixed worker explicitly advertises database-backup-create-v1. The browser supplies no path, filename, database name, command, arguments, schedule, or restore input. The fixed operation has a 50 GiB output ceiling. While a request is pending or processing, the page refreshes its status automatically and stops polling at completion or failure. It reports the last status, time, basename, verified size, and a sanitized error; checksums and protected operational details remain outside browser state.",
            "The database-backup button remains disabled when that exact worker capability is absent or stale. Shipping the application control plane alone does not install the reviewed fixed adapter, runtime tooling, approved backup-root implementation, or verification receipt. The reviewed worker is active and capability-validated on staging and production. On August 2, the first authorized production request completed once and verified alpr-postgres-20260802T164636Z-1.dump at 61.8 MB with no reported error. The worker role has only narrow access to the dedicated request queue; the fixed host adapter performs the dump against the exact database container.",
            "All host schedules default off. Docker cache and backup retention require different one-time activation phrases. Unused-image scheduling is unsupported, and backup cleanup never deletes images. The manual image-retirement grace defaults to seven days and can be changed from one to 365 days only with Administrator approval and the displayed typed phrase. Application and maintenance-worker images use separate append-only ledgers, and the current attested worker is protected. A reviewed worker may adopt only exact, verifiable legacy identities where rollback references are fully accounted for; unknown production application images remain protected and block preview. If the worker is not installed or its heartbeat is stale, the controls fail closed and a rate-limited maintenance alert is raised when scheduled work depends on it.",
            "When a host category's safety breaker is open, an Administrator with automatic-cleanup approval permission must type that category's displayed acknowledgement phrase. The server locks the current breaker and accepts acknowledgement only when the failed destructive receipt belongs to that breaker and a newer healthy worker heartbeat and inventory exist. Success appends immutable actor and worker evidence, closes only that breaker, keeps every host schedule disabled, deletes nothing, and requires a separately queued read-only preview before any cleanup request.",
            "Backup retention always protects the newest five verified backups and every verified backup newer than 30 days, plus current and rollback chains. The worker rejects partial, corrupt, foreign, manifestless, symbolic-link, hard-link, or identity-drifted backups. Current/prepared releases, the exactly attested current maintenance worker, database data, captures, volumes, container references, leases, and unknown images remain protected. An environment-specific worker installation may append exact pre-control-plane identities as retired metadata only when immutable labels match and rollback references are fully accounted for; production leaves unknown application images protected. Adoption deletes nothing and starts the configured grace.",
            "An unused-image preview reports the logical size of eligible image identities for cap enforcement; it is not a promise of filesystem space. After each exact deletion, the locked worker measures Docker's layer-store size before and after the operation and reports only the conservative Docker-accounted decrease, capped by that candidate's logical size. Shared layers can therefore make actual reported reclaim smaller than the preview, including zero.",
            "PostgreSQL maintenance information is observational only: the page reports database/table tuple statistics, recent autovacuum/autoanalyze activity, tables with material dead-tuple ratios, and transaction-ID age. It does not execute VACUUM or ANALYZE.",
            "Source images, thumbnails, database rows, referenced captures, Docker volumes, containers, networks, current or prepared releases, and protected rollback backups have no deletion action in this workflow. When the fixed host worker is installed, only preview-confirmed category candidates can be requested. Manual database-backup creation is a separate fixed operation, while restore preflight and restore execution remain external operations.",
            "Users without maintenance management permission can inspect this status but cannot delete or modify images.",
            "Maintenance email and signed-webhook alerts use durable retries and a per-event cooldown. Test email uses the saved SMTP configuration and the recipients currently entered on the page without saving the policy, and shows its result inside the Email alerts card. The maintenance webhook destination is write-only: the page reports only whether one is configured and provides separate Replace, Test, and Clear controls with results inside the Webhook alerts card. Ordinary policy saves preserve the saved destination. Queued alerts resolve the current destination immediately before each send; clearing it retires unsent webhook deliveries so an old URL is not retried. A request already in flight during Replace or Clear may still finish at the prior destination. Warning-to-critical escalation and recovery are not hidden by repeat-warning rate limiting. A stale heartbeat can detect a stopped maintenance loop while the app is alive; whole-app or host outages still require an external uptime monitor.",
          ],
        },
        {
          type: "bullets",
          title: "Safe release process",
          items: [
            "Administrators can read installed release information under Settings > Release, including the application version, deployment-provided Git SHA, release channel, and local release notes.",
            "Commit-pinned Docker builds embed their exact checked-out SHA and branch channel without retaining Git history in the runtime image. ALPR_RELEASE_SHA and ALPR_RELEASE_CHANNEL remain explicit deployment overrides; no network lookup or mutable-state guess is used.",
            "Changes are tested on a feature branch, validated by tests/typecheck/lint/build/security checks, and deployed to isolated staging first.",
            "Production deployment requires explicit approval, a verified PostgreSQL backup, an exact commit/image, one migration run, app-only restart when possible, health checks, and bounded log review.",
            "Vehicle View migrations remain idempotent when overview work already exists: every queue-kind constraint accepts the overview value and every status constraint accepts active processing before later migration blocks inspect or replace those constraints.",
            "Every production candidate updates this help manual and the product roadmap in the same release so current behavior and remaining work stay aligned with production.",
            "Application rollback returns to the recorded previous image. A runtime rollback does not automatically reverse database migrations.",
            "The website does not provide an arbitrary SQL shell, host shell, or unrestricted Docker update button.",
          ],
        },
        {
          type: "note",
          tone: "warning",
          title: "Legacy migration pages",
          text: "Backfill, JPEG migration, and Update pages are specialized maintenance tools, not routine navigation. Use them only with a current backup and a release-specific procedure.",
        },
      ],
    },
    {
      id: "troubleshooting",
      title: "Troubleshooting",
      summary: "Collect useful evidence without exposing credentials or changing data unnecessarily.",
      roles: allRoles(),
      keywords: ["troubleshooting", "error", "health", "support", "browser", "logs"],
      blocks: [
        {
          type: "steps",
          title: "When a page does not behave as expected",
          items: [
            "Confirm the signed-in username and role, then decide whether the behavior is a permission boundary or an application failure.",
            "Reload once and reproduce the smallest failing action. Record the page, time, selected filters, and exact visible error.",
            "Check the health endpoint or ask an Administrator to review System Logs and the bounded container logs for the same time.",
            "Capture a screenshot only after checking that it contains no password, session, API key, broker secret, private plate image, or unnecessary personal data.",
            "Do not refresh datasets, prune Docker, edit database rows, rerun migrations, or redeploy repeatedly merely to see whether the problem disappears.",
          ],
        },
        {
          type: "bullets",
          title: "Useful problem report",
          items: [
            "Application release or commit, browser/device, signed-in role, page, local timestamp, expected result, actual result, and reproduction steps.",
            "Whether the failure affects one account, one camera, one plate, or all activity.",
            "Whether a recent configuration, migration, or deployment preceded the problem.",
          ],
        },
      ],
    },
    {
      id: "visual-search",
      title: "Visual vehicle search",
      summary: "Compare local derived vehicle crops while keeping original captures unchanged.",
      roles: allRoles(),
      keywords: ["visual search", "vehicle image similarity search", "vehicle crop", "vehicle reid", "openvino", "duplicate", "camera filter"],
      blocks: [
        {
          type: "steps",
          title: "Find captures that look similar",
          items: [
            "Open a capture from Recognition Feed or Plate Database, then choose Find similar vehicle. You can also choose a recent indexed capture or upload a JPEG, PNG, or WebP vehicle image up to 5 MB in Visual Search.",
            "Uploaded queries are validated, decoded, and compared transiently. They are not stored as plate reads or written to the image library.",
            "Optionally narrow results by one or more cameras and a date range, then apply the filters.",
            "Review Vehicle ReID candidates visually. The learned image-embedding score is independent of plate text; the displayed plate is only a link to supporting capture history.",
            "Administrators and Operators can label a stored-source result Same vehicle or Different vehicle. Select the other choice later to correct a label; every change is retained in the audit history.",
            "Use Plate details to inspect the candidate's exact plate history and full capture context.",
          ],
        },
        {
          type: "bullets",
          title: "Index and score behavior",
          items: [
            "A resumable background worker indexes the newest unindexed captures automatically without making ingestion wait. Administrators can select a gentle, balanced, or fast pace, pause or resume the worker, and run one batch immediately.",
            "Automatic indexing pauses before a batch when free storage or system load crosses its configured safety threshold, then retries after the system recovers.",
            "OpenVINO scans the complete capture first, detects and tightly crops the vehicle, then vehicle-reid-0001 stores a normalized 512-value descriptor. A SHA-256 source hash separately identifies byte-for-byte duplicate captures.",
            "Automatic vehicle detection reports success and fallback counts per camera. It recommends review only after a meaningful sample shows recurring detector misses.",
            "Advanced camera fallback settings remain collapsed during normal use. Full image is the default; plate-centered adaptive or custom framing is used only when the detector cannot isolate a vehicle.",
            "Saving a fallback profile creates a new profile revision and reindexes only that camera's next 20 captures. Original capture images are never changed.",
            "Plate values never affect result inclusion, score, order, or labels. They are displayed only so a person can inspect the candidate's plate history.",
            "Search compares cosine similarity across at most 5,000 recent filtered indexed captures. Percentages rank candidates; only Exact duplicate is an identity claim.",
            "Match calibration summarizes local same/different labels for the current embedding model. Its candidate threshold is analysis only and never changes ranking or identity labels automatically.",
          ],
        },
        {
          type: "steps",
          title: "Configure vehicle direction by camera",
          items: [
            "Administrators open Settings > Vehicle Setup. Use the route-backed Cameras, Vehicle Views, Processing, and Calibration tabs to work on one task at a time. Each tab loads only the records and status information needed for that task, so opening one setup page does not wait for the other three setup workloads. The main Vehicle Intelligence workspace paints its primary controls before optional camera detector previews are scanned, and routine status refreshes do not repeat those image scans. Each camera-specific setup page shows its own camera selector; camera names and direction meanings are never built into the application. On desktop, the Settings sidebar can collapse to an icon rail without changing the current page.",
            "Enter what a visible vehicle front means for that camera and what a visible rear means. These may be compass directions such as Eastbound and Westbound or site meanings such as Entering driveway and Exiting driveway.",
            "Enter the exact reverse Blue Iris zone crossings for those two meanings and enable zone-crossing direction after live verification. New daytime mapped crossings are authoritative; Vehicle ReID is retained for reads where the crossing is unavailable or unmapped. Blue Iris 6 may expand &TYPE into a descriptive list such as Motion_A>B,Zone A,Zone B; ALPR retains that complete sanitized receipt evidence and uses only its valid leading ordered crossing for direction. Conflicting or unsafe crossing evidence remains unavailable. Monochrome nighttime captures are not classified.",
            "Choose a minimum confidence. Results below it remain Unknown instead of being forced into a direction.",
            "Label at least three clear front views and three clear rear views from that camera. Add more examples covering ordinary light, weather, distance, and vehicle shapes to improve local calibration.",
            "Save the camera setup. Recent indexed captures are reevaluated immediately, and the remaining historical reads are queued for the paced background worker.",
            "Historical image-backed reads are evaluated automatically after Vehicle ReID indexing. This page shows assigned, Unknown, pending, and failed totals and lets an administrator run one bounded batch immediately.",
            "After adding or changing calibration examples, use Re-evaluate selected camera or Re-evaluate all cameras to preview the affected counts and queue completed machine-generated results for another pass. Current direction assignments stay visible until their replacements are ready, and human front/rear reviews are preserved.",
            "Use Pause re-evaluation to stop historical rechecks after the current bounded batch, and Resume re-evaluation to continue later. Newly ingested reads remain prioritized and continue receiving direction analysis while historical work is paused.",
            "A new daytime mapped Blue Iris crossing displays its direction immediately. A fallback ReID read displays Pending until analysis finishes; Unknown means fallback analysis completed without enough confidence. A monochrome nighttime read displays Unavailable nighttime. Live Feed refreshes these results while Live Updates is enabled.",
            "The historical process resumes from durable queue state after a restart, retries an individual failure up to three times, preserves human front/rear reviews, and never sends historical direction notifications.",
          ],
        },
        {
          type: "steps",
          title: "Configure daytime Vehicle Views",
          items: [
            "Open Settings > Vehicle Setup > Vehicle Views and configure Street Overview for each Street LPR camera/direction and Entry Overview for each Entry LPR camera/direction. Entry mappings use the Blue Iris short name Cam143 and are stored separately from Street mappings.",
            "Enter the measured signed timing delta and a primary tolerance from 250 through 3000 milliseconds for each camera pair. The tolerance positions the exact 61-sample window around the calculated anchor. A lower priority number wins when otherwise comparable source profiles overlap.",
            "The Vehicle View source camera must differ from the plate camera. Legacy primary profiles above 3000 milliseconds or legacy same-camera rows are preserved during migration but remain unclaimed until an administrator corrects and saves them.",
            "Measure and save four Entry primary mappings when all directions are used: Entry LPR 1 Entering, Entry LPR 1 Exiting, Entry LPR 2 Entering, and Entry LPR 2 Exiting. Do not guess the signed delta or widen tolerance merely because Entry traffic is sparse.",
            "Configure Entry LPR route fallback separately after the primary and companion paths are validated. Each route requires an existing Street target read, two configured Entry LPR camera slots, one Entering or Exiting direction, a signed Entry-event-minus-Street-read delta, and a bounded timing window. Runtime matching prefers evidence from both cameras but may use one direction-authoritative Entry read under the stricter identity, timing, payload, and ambiguity safeguards. The separately guarded Cam143 payload may copy only the ready daytime Entry Overview image belonging to that authoritative read.",
            "Do not create a separate overview-camera motion action. The existing Street or Entry LPR plate action anchors direct timeline retrieval from its configured overview source.",
            "Watch queued, ready, unavailable, and ambiguity outcomes. Tune the signed timing delta from evidence rather than widening every tolerance.",
            "A fresh transient recording, export, download, or media failure receives one automatic delayed retry. A repeated transient failure is terminalized, while no viable vehicle and competing viable vehicles remain separate fail-closed outcomes. Persisted selection and export diagnostics distinguish these cases.",
            "Set the Blue Iris timeline export compatibility profile and minimum accepted dimensions under Settings > Blue Iris. ALPR requests the recorded main stream with re-encoding disabled and verifies the actual result rather than assuming native resolution. A saved Vehicle View uses the exact selected full-resolution slot from the verified export, while low-resolution exports are rejected rather than silently stored.",
            "Each read and source window has one stable automatic export identity. If Blue Iris reports a rejection after the request was dispatched, ALPR waits five seconds between checks and adopts the one new exact camera, start-time, and duration match instead of submitting another export. During upgrade recovery, equivalent retained legacy duplicate exports may be reused, but uncertain or competing non-equivalent jobs remain unavailable rather than generating more Clipboard files.",
            "The worker claims overview reads oldest first, refreshes a short processing lease while it owns the read, and also enforces a non-extendable five-minute deadline. Before using Recover incomplete overview jobs, enter the exact local date and time at which trusted Blue Iris direction data began. Recovery applies only to pending, stuck, or transient operational failures while Blue Iris retention still covers them. It is one-time per read and never resets itself indefinitely; ready images, nighttime reads, ambiguity, and resolution/configuration failures are preserved.",
            "Select Preview incomplete jobs first. The preview is read-only and must still match the entered start time before Queue is enabled. Timeline exports remain owned per plate read, so two successful Street LPR reads may each create one export. Street LPR companion sharing runs only after a safe terminal miss and reuses the successful read's stored JPEG; it does not delay or coalesce fresh primary exports.",
            "If Blue Iris 6 composite trigger values caused reads to miss direction before compatibility was installed, use Repair missed Blue Iris 6 composite triggers. Enter the affected start time and preview first. ALPR requires one retained accepted ingress receipt linked to the exact read, the unchanged camera mapping revision, no human direction label, and the original never-started overview state. Repair revalidates the preview in batches of at most 250, restores the mapped direction, queues the normal overview worker, records audit and read-timeline evidence, and never replays historical notifications. Repeat preview and repair until no eligible reads remain.",
            "Use Entry Overview history for retained Entry LPR 1/2 upgrades, including authorized reads that predate reliable direction labels. Its start and exclusive end form a frozen campaign scope. Preview before every campaign, validate small canary batches, then use explicit batches of up to 250 reads until no previewable reads remain. The generic camera-history action continues to sample the selected plate camera and is intentionally blocked for Entry LPR cameras covered by this Cam143 workflow.",
            "Keep Street LPR companion sharing in Shadow proposals only during its first production observation. Review proposed and rejected decisions under Vehicle Views. Switch to Active only after exact live pairs have been verified; Active still leaves ambiguity, multi-vehicle, nighttime, direction, profile, and configuration failures unchanged.",
            "Keep both Entry LPR route matching and its Cam143 payload guard in Shadow while validating rare driveway events. Review the source and corroborating read IDs, Cam143 payload read and provenance, route timing, plate evidence class, and rejection reason. Active remains read-to-read only and never creates a Street event from an Entry capture.",
            "Verify daytime examples in Recognition Feed. Nighttime plate reads display Unavailable nighttime and do not run Vehicle View frame analysis or contact Blue Iris for timeline frames.",
          ],
        },
        {
          type: "note",
          tone: "warning",
          title: "Direction source and fallback",
          text: "Validated Blue Iris ordered zone crossings are authoritative for new daytime mapped reads. Single-frame Vehicle ReID remains a conservative fallback when Blue Iris does not supply a usable crossing; it stores no video clips and leaves uncertain daytime captures Unknown. Monochrome nighttime captures display Unavailable nighttime and are not classified. Historical reads and legacy shadow evidence are not reinterpreted when primary direction is enabled.",
        },
        {
          type: "steps",
          title: "Build the canonical Overview catalog",
          items: [
            "Administrators open Settings > Vehicle Setup > Processing and use Canonical Overview catalog. Select Create catalog preview first. The preview freezes every currently eligible ready Entry or Street Overview read that lacks a current exact link, hashes and validates its JPEG in a durable low-priority worker, and creates no canonical files or read links.",
            "Wait for Ready, then review the exact unique-JPEG count, reusable assets, one-time active-campaign storage projection, duplicate-copy bytes avoided, identity-eligible links, display-only links, missing sources, invalid images, and stale-link repairs. Existing read-owned Vehicle Views remain in place, so additional storage is growth rather than reclaimed space.",
            "Choose a canary batch of 1, 5, 25, or 250 and select Catalog next batch. Before any write, ALPR rereads the source, requires the frozen SHA-256, byte size, dimensions, path, source kind, and exact source revision, then publishes one immutable content-addressed JPEG and links every byte-identical read to that asset.",
            "Use Pause or Resume between bounded batches, Cancel remaining to preserve completed assets while stopping unstarted items, and the one bounded operator retry only for listed terminal operational failures. A changed read or changed JPEG is reported as superseded and is never silently cataloged under the old preview.",
            "After the initial campaign completes, turn on Automatic new Overview cataloging if continuous local cataloging is wanted. It is default-off, claims only newly ready or changed eligible Overview reads, uses the same exact-JPEG asset and current-source checks, and pauses itself while an operator preview or catalog campaign is active.",
            "Automatic work is durable and bounded. Disabling it prevents new claims while allowing an already claimed item to finish safely. Review queued, processing, unavailable, failed, and pending-eligible counts on this card; one listed terminal operational failure may receive one operator retry.",
            "When automatic cataloging is enabled, Storage Health includes its observed canonical bytes per current link in recurring growth projections. Create delta preview remains disabled until automatic cataloging is turned off, so the operator campaign and automatic queue cannot compete for the same reads.",
            "Superseded and zero-link canonical assets are retained as archival evidence; this page has no asset deletion control.",
          ],
        },
        {
          type: "note",
          tone: "info",
          title: "Catalog scope does not change vehicle intelligence yet",
          text: "The canonical catalog deduplicates exact Overview bytes and preserves Entry or Street provenance, but current Vehicle ReID, clusters, attributes, Vehicle Profiles, and Recognition Feed behavior remain unchanged. Entry-to-Street display fallback images remain display-only and cannot count as a second identity observation. The catalog is local and makes no Plate Recognizer or other external enrichment call.",
        },
        {
          type: "steps",
          title: "Create canonical Overview vehicle crops",
          items: [
            "Administrators open Settings > Vehicle Setup > Processing and use Canonical Overview vehicle crops. Select Create crop preview first. The background preview freezes each eligible identity asset, its current evidence read, its validated Overview vehicle box, and the exact canonical source revision without writing a crop file.",
            "When the preview is Ready, compare source pixels with crop pixels and review unique crop files plus projected physical storage. The crop is a new local derivative: the full canonical Overview remains retained, so this does not reclaim the source image's storage.",
            "Choose a canary of 1, 5, 25, or 250 assets and select Create next crop batch. ALPR rereads and re-hashes the source, verifies its dimensions and frozen vehicle box, renders the same padded crop again, and publishes one immutable content-addressed JPEG only when every preview field still matches.",
            "After each canary finishes, inspect Recent canonical crops before creating a larger batch. Use Pause or Resume between batches, Cancel remaining to stop unstarted work, and the listed one-time retry only for a terminal operational failure. Missing or invalid boxes, changed sources, and changed crop output fail closed rather than falling back to a plate image or the full frame.",
            "Review canonical crop count and physical bytes in Storage Health. Reconciliation and cleanup treat every registered derivative path as referenced; no crop deletion or retention control is added in this slice.",
          ],
        },
        {
          type: "note",
          tone: "info",
          title: "Crops prepare ReID v2 but do not enable it",
          text: "Canonical crops are owned by the deduplicated Overview asset and can later feed one embedding or attribute result per asset. This slice does not replace current read-owned ReID, change vehicle assignments, consume shadow-event thresholds, alter notifications, or contact Plate Recognizer or any other external provider.",
        },
        {
          type: "steps",
          title: "Observe shadow vehicle events",
          items: [
            "Administrators open Settings > Vehicle Setup > Processing and use Shadow vehicle events. The control is default-off and cannot be enabled until a canonical Overview catalog campaign has completed.",
            "Enable shadow correlation only when the canonical catalog is current. The low-priority worker waits 20 seconds, then considers current identity-eligible Entry or Street asset links in bounded 25-observation batches.",
            "A pair requires the same exact effective plate and context, different LPR cameras, and the configured conservative read window. Exact shared canonical bytes are preferred. Distinct assets additionally require matching ready direction and Overview capture times within 1.5 seconds.",
            "Review proposed and rejected decisions from this card. Conflicting direction, missing corroboration, competing companions, cross-context evidence, display-only Entry-to-Street fallbacks, and changed source revisions fail closed.",
            "If a linked read, asset, plate, camera, direction, source revision, source-read provenance, or capture time later changes, the prior shadow event is retired and its reads become eligible for fresh shadow evaluation.",
          ],
        },
        {
          type: "note",
          tone: "warning",
          title: "Shadow events are evidence only",
          text: "Shadow vehicle events do not replace plate reads, Vehicle Views, current ReID, clusters, attributes, notifications, or review decisions. They do not contact Plate Recognizer or any other external provider, and disabling the worker leaves recorded evidence intact.",
        },
        {
          type: "steps",
          title: "Review vehicle profiles and plate associations",
          items: [
            "Open Visual Search > Needs Review. This top navigation tab keeps outstanding decisions separate from the Vehicle Profiles list. Vehicle Profiles selects the requested page before aggregating its capture and plate details, while Needs Review loads only the selected Vehicle Matches, Plate Associations, Directions, or Setup Attention queue instead of waiting for every queue at once.",
            "Administrators can analyze the next bounded batch of unassigned indexed captures. The grouping score uses only Vehicle ReID descriptors; plate text is excluded.",
            "Compare each new capture with the cluster representative. Choose Confirm vehicle when they show the same vehicle, or Different vehicle to move the capture into a separate shadow cluster.",
            "Compare the profile representative with the plate evidence in the Plate associations queue. Confirm association creates the trusted baseline, while Reject association preserves the ReID profile and records the rejection.",
            "For Direction reviews, inspect the complete capture and choose Front view or Rear view. The reviewed example is added to that camera's calibration and the displayed direction is recalculated from the camera setup.",
            "Choose Vehicle Matches, Plate Associations, Directions, or administrator Setup Attention. Only the selected queue is displayed, and its count covers the full database rather than only the current page.",
            "Each review queue has its own Previous and Next controls, so completing or paging one queue does not move the others.",
            "The Vehicle profiles list shows 50 profiles per page. Use its status, camera, and search filters to narrow the list, then use the independent profile pagination controls to inspect all matches beyond the first 100.",
            "Administrators also see Camera setup needs attention when direction meanings, training examples, or detector fallback settings need work.",
            "Shadow means the ReID grouping is a candidate for review, not a vehicle ownership or plate-mismatch claim.",
            "The Recognition Feed image popup shows a Vehicle number, assignment state, ReID score, per-read color and coarse vehicle-type estimates, and direction when available. Type inference runs locally and automatically; low-confidence results remain Unknown.",
          ],
        },
        {
          type: "note",
          tone: "warning",
          title: "Mismatch alerts remain disabled",
          text: "Confirmed plate associations establish an auditable baseline, but profiles do not yet send mismatch notifications or label a plate as switched or stolen. Automated mismatch rules remain a later calibrated phase with minimum evidence and confidence safeguards.",
        },
        {
          type: "note",
          tone: "warning",
          title: "Visual similarity is not identity",
          text: "Two similar-looking vehicles may be different, and one vehicle may look different across angle, light, weather, or camera. Confirm the original images and surrounding evidence.",
        },
      ],
    },
    {
      id: "planned-features",
      title: "Planned features that are not available yet",
      summary: "Avoid confusing roadmap ideas with current production behavior.",
      roles: allRoles(),
      keywords: ["roadmap", "planned", "vehicle ai", "image search", "overlay", "advanced notifications", "storage"],
      blocks: [
        {
          type: "bullets",
          title: "Planned, not current",
          items: [
            "Additional notification conditions such as rarity, site/direction, and vehicle attributes.",
            "Vehicle make, model, and year enrichment with confidence and model/provider provenance. Coarse car, van, truck, or bus type is already automatic and local.",
            "Expanded camera-pair Vehicle ReID calibration and optional make, model, color, coarse type, and year filters.",
            "Controlled VACUUM ANALYZE, backup catalog integration, restore preflight and execution, automatic backup scheduling, and broader backup-verification jobs.",
            "Configurable image overlays rendered non-destructively at view or export time.",
            "Background capture-image ZIP exports and richer release history beyond the installed read-only release summary.",
          ],
        },
        {
          type: "note",
          tone: "info",
          title: "Roadmap status",
          text: "A roadmap entry explains intended architecture; it does not mean the feature is installed. This section will shrink as features pass staging acceptance and reach production.",
        },
      ],
    },
  ],
});

export function manualSearchText(section) {
  const values = [section.title, section.summary, ...(section.keywords || [])];
  for (const block of section.blocks || []) {
    values.push(block.title, block.text, block.scenario, block.result);
    values.push(...(block.items || []), ...(block.steps || []));
  }
  return values.filter(Boolean).join(" ").toLowerCase();
}
